### ISSUE TITLE
-4 Device connection lost error on Nvidia

### ISSUE THREAD

**Issue by polarbub** [xCollateral/VulkanMod#1]
Driver version 510.60.02
GTX 960 4GB
Mod version 0.1.1 from 1649948400 (unix time stamp)

https://youtu.be/D48ssEjOgCI

https://pastebin.com/a7iRpVjp

**Comment by 19MisterX98** [comment]
Same crash on Windows 10
GTX660M
Mod version 0.1.1+2
https://paste.ee/p/0jiQ8

**Comment by polarbub** [comment]
0.1.1+2 still crashes https://paste.ee/p/vmFWz

**Comment by polarbub** [comment]
> Same crash on Windows 10 GTX660M Mod version 0.1.1+2 https://paste.ee/p/0jiQ8

https://pastebin.com/zqx7htEi pastebin link that won't expire

**Comment by BayuLewis** [comment]
It has been fixed with the [latest build](https://github.com/xCollateral/VulkanMod/releases/tag/0.1.2). Singleplayer works normally without any crashes.
