### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ItsMrHalp** [xCollateral/VulkanMod#105]
Crash while loading
[hs_err_pid1656.log](https://github.com/xCollateral/VulkanMod/files/9500380/hs_err_pid1656.log)

**Comment by ItsMrHalp** [comment]
no any addition mods was installed

**Comment by Etaash-mathamsetty** [comment]
could you give a game log, if it's a crash while loading it might be related to #94

**Comment by ItsMrHalp** [comment]
For some reason, the game log was not created, and when I installed everything clean(Before that, there were modpacks on fabric with mods on 1.18.2 and 1.17.1, I deleted the mods themselves, but it looks like some residual files remained), it decided to start working

**Comment by xCollateral** [comment]
If you are using fabulous graphics then that's the issue.
