### ISSUE TITLE
i have a error 1 when i launch minecraft on PolyMC or MultiMC

### ISSUE THREAD

**Issue by DefliXXX** [xCollateral/VulkanMod#106]
[https://youtu.be/20Ve7_-ego4](url)
[crash-2022-09-11_11.53.55-client.txt](https://github.com/xCollateral/VulkanMod/files/9542271/crash-2022-09-11_11.53.55-client.txt)
i use Java 17

**Comment by xCollateral** [comment]
Your gpu does not support Vulkan.
