### ISSUE TITLE
Add support with sodium

### ISSUE THREAD

**Issue by sasa8810** [xCollateral/VulkanMod#108]
Coexist with sodium and make it even faster.

**Comment by jumpers775** [comment]
cannot be done. this replaces the renderer with vulkan, a more modern and faster renderer than opengl. sodium replaces it with a custom opengl renderer. opengl and vulkan cannot coexist.

**Comment by Fox2Code** [comment]
Actually, it is kind of half possible, sodium expose a way to disable parts of it's code/mixins, so it would be possible to disable the parts of Sodium not compatible with VulkanMod.

Sure it will make sodium not 100% because some part of sodium will be disabled, but it is possible.

**Comment by UltraBlackLinux** [comment]
I was told that iris does some vulkan stuff, so you might just get away with using that

**Comment by CuteistCat** [comment]
> I was told that iris does some vulkan stuff, so you might just get away with using that

im pretty sure its fully opengl unless extensions are used

**Comment by CuteistCat** [comment]
> Actually, it is kind of half possible, sodium expose a way to disable parts of it's code/mixins, so it would be possible to disable the parts of Sodium not compatible with VulkanMod.
> 
> Sure it will make sodium not 100% because some part of sodium will be disabled, but it is possible.

Well that is not going to be usefull becuase all the optimisations oof sudium that work with vulkan mod are implented by standalone mods

**Comment by err2ror** [comment]
can sm1 close this as not planned
im an idiot seeing how much people want sodium + vulkanmod
to that i say
https://github.com/xCollateral/VulkanMod/wiki/Incompatible-mods
