### ISSUE TITLE
Entity render limit?

### ISSUE THREAD

**Issue by tr7zw** [xCollateral/VulkanMod#11]
When creating a chest cube with ``/fill ~ ~ ~ ~25 ~25 ~25 minecraft:chest``, this cube will only render partially, while creating broken chests and a lot of lag.
![grafik](https://user-images.githubusercontent.com/5133936/166808243-3b030678-952d-40c6-90da-3160fd939b66.png)

**Comment by ProgrammerIn-wonderland** [comment]
Chests aren't an entity (to my knowledge)

**Comment by ProgrammerIn-wonderland** [comment]
The issue could be with transparent blocks, try it with ferns and grass and glass etc

**Comment by tr7zw** [comment]
> Chests aren't an entity (to my knowledge)

Chests are BlockEntities and rendered the exact same way as Entities.

**Comment by ProgrammerIn-wonderland** [comment]
Oooo, what happens if you try spawing other entities like armor stands?
