### ISSUE TITLE
ManyMC is no longer supported. (for MacOS instructions)

### ISSUE THREAD

**Issue by jordoncodes** [xCollateral/VulkanMod#112]
![SCR-20221003-qxb](https://user-images.githubusercontent.com/98439832/193543770-76366063-6f19-42e7-819e-27e084b3050a.png)

ManyMC is no longer supported
VVV

![SCR-20221003-qyf](https://user-images.githubusercontent.com/98439832/193543972-451618a6-1365-4cb6-8ae5-3649c60f6201.png)

**Comment by prpjzz** [comment]
Since most MC Multi Launcher are based on MultiMC, only different in some places, you can do the instructions in ManyMC above other Multi Launcher, such as Poly.
