### ISSUE TITLE
A crash on start-up

### ISSUE THREAD

**Issue by allen-li-qwq** [xCollateral/VulkanMod#113]
I only added this mod to the mod folder, but it still made my game crashed without any information.
I really love this mod, but it can't work well on my PC. Thanks! 

Game version: Minecraft 1.18.2 with fabric 0.14.9.
CPU:                Intel Core i7-6600U ( 2 cores 4 threads)
Memory:         16GB LPDDR3
Graphics:         Intel HD Graphics 520
Java:                Hotspot, jdk-17.0.4.1
Operating system:          Windows 10 Enterprise (21H2)

**Comment by xCollateral** [comment]
Without logs i can't help much. Try updating your graphics driver and send log if it keep crashing.
