### ISSUE TITLE
Incompatible Mod Set: 'VulkanMod' 0.1.5+2 requires any 1.18.x version of 'Minecraft', but only the wrong version is present: 1.19.2!

### ISSUE THREAD

**Issue by Konglomneshued** [xCollateral/VulkanMod#119]
Your mod on Modrinth is listed as 1.18-1.19, so I don't understand why I am receiving this error.  It's telling me it requires 1.18.

**Comment by xCollateral** [comment]
Modrinth version is outdated. Download it from Curseforge and choose the version that matches the minecraft version you're trying to run.

**Comment by Felix14-v2** [comment]
> Modrinth version is outdated

Can you upload the new version? CurseForge is just terrible to use.
