### ISSUE TITLE
Crashes when tesselating blocks

### ISSUE THREAD

**Issue by headassbtw** [xCollateral/VulkanMod#12]
happens on both [1.17.1](https://paste.ee/p/Ob9jV) and [1.18.2](https://paste.ee/p/okaw8), crashes at the same step, 100% of the time, when loading into a world

system:
OS: arch linux
CPU: ryzen 5 3600
GPU(s): RTX 2070, GTX 1050 Ti (would not be surprised if the second card is causing this, but it gives me slightly faster blender renders and a flex in neofetch, so i'd prefer to keep it in

**Comment by xCollateral** [comment]
If you are using frabric api you have to set _always-tesselate-blocks=false_ in _config/fabric/indigo-renderer.properties_

**Comment by headassbtw** [comment]
yep worked, thanks
