### ISSUE TITLE
Always crashes on Linux

### ISSUE THREAD

**Issue by Belt-Buckle** [xCollateral/VulkanMod#121]
Yes, I know Linux and Mac aren't _technically_ supported but anyway,
I literally can't get the mod to work (unless I disable fabric in which case the mod isn't even active)
system info: Fedora 37 beta, normal launcher (tried PolyMC 1.4.2), 1.19.2 (tried 1.19.1, 1.19, and 1.18.2), Fabric 0.14.9 (tried 0.14.8 as well) Java 17.0.4.1, Ryzen 5850u (laptop igpu), 32gb of RAM

The window opens for a moment before freezing and crashing. I've had extremely limited success, as in getting the progress bar slowly moving about 5/6 of the way before freezing and crashing, but I have no clue how to replicate that

Crash log:
[crash-2022-10-11_18.18.11-client.txt](https://github.com/xCollateral/VulkanMod/files/9760056/crash-2022-10-11_18.18.11-client.txt)

**Comment by xCollateral** [comment]
Log is empty, are you getting the same as #94 ?

**Comment by Belt-Buckle** [comment]
That looks exactly the same as the crash log I'm seeing. I'd also like to point out that we're both using AMD laptop APUs on linux for whatever that's worth.

**Comment by Belt-Buckle** [comment]
Got around to getting on my laptop, here's the crash report in text form.
`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-10-11 18:18:11
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.vulkanmod.vulkan.Drawer.initiateRenderPass(Drawer.java:189)
	at net.minecraft.class_310.handler$zze000$beginRender(class_310.java:3002)
	at net.minecraft.class_310.method_1523(class_310.java:1165)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.vulkanmod.vulkan.Drawer.initiateRenderPass(Drawer.java:189)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2348)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.19.14-300.fc37.x86_64
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1030413368 bytes (982 MiB) / 2818572288 bytes (2688 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 PRO 5850U with Radeon Graphics
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Cezanne
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 23901.06
	Virtual memory used (MB): 8844.42
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics`

**Comment by Etaash-mathamsetty** [comment]
> Got around to getting on my laptop, here's the crash report in text form.
> 
> ```
> // I let you down. Sorry :(
> 
> Time: 2022-10-11 18:18:11
> Description: Unexpected error
> 
> java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
> 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
> 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
> 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
> 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
> 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
> 	at net.vulkanmod.vulkan.Drawer.initiateRenderPass(Drawer.java:189)
> 	at net.minecraft.class_310.handler$zze000$beginRender(class_310.java:3002)
> 	at net.minecraft.class_310.method_1523(class_310.java:1165)
> 	at net.minecraft.class_310.method_1514(class_310.java:768)
> 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
> 	at net.minecraft.client.main.Main.main(Main.java:51)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
> 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
> 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
> 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
> 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
> 	at net.vulkanmod.vulkan.Drawer.initiateRenderPass(Drawer.java:189)
> 
> -- Last reload --
> Details:
> 	Reload number: 1
> 	Reload reason: initial
> 	Finished: No
> 	Packs: Default
> Stacktrace:
> 	at net.minecraft.class_6360.method_36565(class_6360.java:49)
> 	at net.minecraft.class_310.method_1587(class_310.java:2348)
> 	at net.minecraft.class_310.method_1514(class_310.java:792)
> 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
> 	at net.minecraft.client.main.Main.main(Main.java:51)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.19.2
> 	Minecraft Version ID: 1.19.2
> 	Operating System: Linux (amd64) version 5.19.14-300.fc37.x86_64
> 	Java Version: 17.0.3, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 1030413368 bytes (982 MiB) / 2818572288 bytes (2688 MiB) up to 6442450944 bytes (6144 MiB)
> 	CPUs: 16
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 7 PRO 5850U with Radeon Graphics
> 	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
> 	Microarchitecture: unknown
> 	Frequency (GHz): -0.00
> 	Number of physical packages: 1
> 	Number of physical CPUs: 8
> 	Number of logical CPUs: 16
> 	Graphics card #0 name: Cezanne
> 	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
> 	Graphics card #0 VRAM (MB): 258.00
> 	Graphics card #0 deviceId: 0x1638
> 	Graphics card #0 versionInfo: unknown
> 	Virtual memory max (MB): 23901.06
> 	Virtual memory used (MB): 8844.42
> 	Swap memory total (MB): 8192.00
> 	Swap memory used (MB): 0.00
> 	JVM Flags: 8 total; -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Launched Version: fabric-loader-0.14.9-1.19.2
> 	Backend library: LWJGL version 3.3.1 SNAPSHOT
> 	Backend API: Unknown
> 	Window size: 854x480
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 	GL debug messages: <disabled>
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Graphics mode: fancy
> 	Resource Packs: 
> 	Current Language: English (US)
> 	CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics```
> ```

yeah this is #94, thanks for confirming that im not the only one with this issue lol

**Comment by Belt-Buckle** [comment]
> I've had extremely limited success, as in getting the progress bar slowly moving about 5/6 of the way before freezing and crashing, but I have no clue how to replicate that
after looking into #94 and confirming that it is indeed the same issue my crash report has, and using the fix described in it, I can consistently replicate the issue I mentioned here. It actually causes Java to crash and report an error to the system.
Crash log:
[hs_err_pid32582.log](https://github.com/xCollateral/VulkanMod/files/9769046/hs_err_pid32582.log)

**Comment by Belt-Buckle** [comment]
just realized it's probably a good idea to include this bit from the minecraft log:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGFPE (0x8) at pc=0x00007f2c28d48c68, pid=14626, tid=14627
#
# JRE version: OpenJDK Runtime Environment (Red_Hat-17.0.4.1.1-3.fc37) (17.0.4.1+1) (build 17.0.4.1+1)
# Java VM: OpenJDK 64-Bit Server VM (Red_Hat-17.0.4.1.1-3.fc37) (17.0.4.1+1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libvulkan_radeon.so+0xf6c68]

**Comment by OCsonic** [comment]
I just tested on Gentoo Linux with an Intel APU (supporting Vulkan 1.2), this particular issue does not appear to occur on my configuration here's a successful log starting up in hopes that this might be able to help somehow in the event that this is a Linux issue : https://mclo.gs/4pRlZGp

**Comment by Belt-Buckle** [comment]
It's working in the latest version so idk what you did but thank you
