### ISSUE TITLE
String visual artifacts

### ISSUE THREAD

**Issue by NtimesN-2** [xCollateral/VulkanMod#122]
To replicate, place down string and look at it while facing west in-game. It's most noticeable if you're looking up at the string.

Tested on a GTX 1650 mobile, on driver versions 516.94 and 522.25.
Minecraft version 1.19.2, mod version 0.18 (untested on other versions).

![string](https://user-images.githubusercontent.com/75134198/195419232-d97fce78-945a-4c12-b709-9d339b4dc71b.png)

**Comment by xCollateral** [comment]
I noticed a bug in 1.19.2 that almost surely caused this. Next build it should be fixed
