### ISSUE TITLE
Linux keybinds messed up

### ISSUE THREAD

**Issue by ProgrammerIn-wonderland** [xCollateral/VulkanMod#126]
Special keys (Space, cntrl, shift, etc) dont work unless you reconfigure them
![image](https://user-images.githubusercontent.com/30693865/196545092-8372c04a-cd1e-451e-9db9-78ac8ab714e4.png)

this issue is manageable by selecting and pressing the key, but there are certain keys you cannot reconfigure (f3, etc, etc)

Device info:
CPU: 1165g7
GPU0 (inactive): Intel Iris Xe
GPU1 (Active): NVIDIA GeForce RTX 3080 eGPU
Ram: 64GB
Distro: Arch Linux
DE: KDE

**Comment by ProgrammerIn-wonderland** [comment]
I should add, I am on Linux-LTS and using nvidia-LTS drivers from the Arch repo

**Comment by ProgrammerIn-wonderland** [comment]
Also, backspace and  enter do not work in ingame text fields (chat, server input, etc)

**Comment by ProgrammerIn-wonderland** [comment]
oh my, the issue was the keyboard layout, though oddly this issue doesn't exist on Sodium

for anyone facing this issue, you need to change your keyboard Locale to English (US). I had mine on English International with Altgr deadkeys, still leaving this open since I'm not sure if keyboard layouts should break vulkanmod

**Comment by xCollateral** [comment]
I think VulkanMod isn't related as it does not modify any keyboard handler classes.
Maybe LWJGL version, which VulkanMod kind of forces, but i'm not sure.
