### ISSUE TITLE
Optimize tablist/chat/hud rendering

### ISSUE THREAD

**Issue by andreasdc** [xCollateral/VulkanMod#128]
![image](https://user-images.githubusercontent.com/82218780/196738725-38fa8b33-aff4-44ba-8815-c281e80c448d.png)
![image](https://user-images.githubusercontent.com/82218780/196738784-6bb6710a-1e26-4a68-b7e1-584bab81f8d0.png)

**Comment by andreasdc** [comment]
![image](https://user-images.githubusercontent.com/82218780/196739088-9b08f754-454f-4650-af3c-0f5dc67a17cd.png)

**Comment by xCollateral** [comment]
Chat and Hud are already optimized when relative setting is enabled.

**Comment by andreasdc** [comment]
What is relative setting?

**Comment by xCollateral** [comment]
Gui Optimizations setting in video setting screen

**Comment by andreasdc** [comment]
I use version before the video settings screen, because it breaks my gamma.

**Comment by andreasdc** [comment]
Completed?

**Comment by xCollateral** [comment]
As I said before they are already optimized, you just have to enable the relative setting(It may cause mod incompatibility though).

**Comment by andreasdc** [comment]
Can it be optimized more? For tablist there are no optimizations, I don't know about scoreboard too.
