### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by andreasdc** [xCollateral/VulkanMod#129]
Will there be 1.19.2 version?

**Comment by Felix14-v2** [comment]
![Uploading Screenshot_20221021-194050.jpg…]()

**Comment by andreasdc** [comment]
It's not up to date to the commits

**Comment by Felix14-v2** [comment]
> It's not up to date to the commits

Lol
Built it for yourself, if you want to have the latest dev-version.

**Comment by andreasdc** [comment]
No

**Comment by Zorklis** [comment]
Solved by VulkanMod 0.1.8
