### ISSUE TITLE
Baked models

### ISSUE THREAD

**Issue by andreasdc** [xCollateral/VulkanMod#132]
Is baked models a thing in VulkanMod? If not can it be?

**Comment by xCollateral** [comment]
I'm not sure what you are referring to. Vanilla Minecraft already uses baked models for some aspects of the game, therefore we do as well.

**Comment by andreasdc** [comment]
> I'm not sure what you are referring to. Vanilla Minecraft already uses baked models for some aspects of the game, therefore we do as well.

I think I saw it here
https://github.com/KilnGraphics/baked-minecraft-models
