### ISSUE TITLE
Crash on 1.19.2 VK-Mod 0.1.8 Fabric 0.14.10

### ISSUE THREAD

**Issue by Blykam** [xCollateral/VulkanMod#135]
I can't start any versions of this mod. It crashes before it loads into the Main Menu.
Has anyone an idea what to do?

[hs_err_pid6172.log](https://github.com/xCollateral/VulkanMod/files/9893929/hs_err_pid6172.log)

**Comment by xCollateral** [comment]
Fabulous graphics is not supported, you'll have to disable it before loading VulkanMod

**Comment by Blykam** [comment]
Thanks. Now it works!
