### ISSUE TITLE
The old graphics settings menu

### ISSUE THREAD

**Issue by forditt** [xCollateral/VulkanMod#143]
Please remove the new graphics settings menu. It does not look beautiful, the standard minecraft menu is much better

**Comment by alyzow** [comment]
It's not about the look, it's about the function built-in. If it works, it works.

**Comment by xCollateral** [comment]
No. It's not only about aesthetics, it's about functionality.

**Comment by forditt** [comment]
> No. It's not only about aesthetics, it's about functionality.

is it possible to make then the design of the menu as in optifine?
