### ISSUE TITLE
1.19.x crash and input latency

### ISSUE THREAD

**Issue by UltraBlackLinux** [xCollateral/VulkanMod#144]
Hey there,
this mod is crashing on every 1.19.x:
[hs_err_pid652814.log](https://github.com/xCollateral/VulkanMod/files/10097095/hs_err_pid652814.log)

Another problem that i noticed is horrendous input delay. If I click or press any button it takes ~300 mills to do that.

I don't really have a clue, how to debug this.

Any ideas about theses?
Thanks!

Edit: Noticed that the index out of bounds issue is something to be solved via the config.

**Comment by xCollateral** [comment]
Try updating mesa driver

**Comment by UltraBlackLinux** [comment]
Well mesa is on 22.2.3-1 for me, which is the most recent version. No clue what else I could do.

**Comment by xCollateral** [comment]
Try forcing `frameQueueSize ` to 2 in config file

**Comment by UltraBlackLinux** [comment]
> Try forcing frameQueueSize to 2 in config file

Just checked the config and it's already set to 2. Tried tweaking the screen size and refresh rate, but it's still crashing. 5 is also crashing.

I also found this error, is that related? 
`[STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.`

**Comment by xCollateral** [comment]
Latest commit should have solved this issue.

**Comment by UltraBlackLinux** [comment]
Well it fixed the issues mentioned here, but caused new ones. Opening a new issue

**Comment by UltraBlackLinux** [comment]
The latency issue does not seem fully resolved on the newest 1.19 version. If I enable Vsync, I can feel some input-latency, but if I disable Vsync I get this kind of frame loss often visible in youtube videos when a game's fps drop below 60 fps (= Frames stuttering back and fourth)
