### ISSUE TITLE
f3+g crashes the game & colors are wrong in screenshots

### ISSUE THREAD

**Issue by isvirki** [xCollateral/VulkanMod#145]
Pressing f3+g to show chunk boundaries crashes the game.

also
Screenshots have their colors off
Wrong one:
![2022-11-27_20 15 58](https://user-images.githubusercontent.com/75780057/204150591-6a5b2799-4d55-4cbd-945e-4193f96bd47b.png)
Correct colors:
![image](https://user-images.githubusercontent.com/75780057/204150610-6f7de5b0-1deb-4d0b-a6fd-ebce25315378.png)

**Comment by isvirki** [comment]
[crash-2022-11-27_20.27.11-client.txt](https://github.com/xCollateral/VulkanMod/files/10098849/crash-2022-11-27_20.27.11-client.txt)
 Here is the crash log

**Comment by xCollateral** [comment]
Both are known issues

**Comment by isvirki** [comment]
> Both are known issues

Thanks for informing me!
