### ISSUE TITLE
MacOS x64 intel "Render pipeline compile failed"

### ISSUE THREAD

**Issue by mintyleaf** [xCollateral/VulkanMod#148]
Hey, just tried hard to launch this mod on my hackintoshed x260
There is missing lwjgl libs from their official site, put if to your fabric [`profile.json`](https://gist.github.com/mintyleaf/57c72f12fedf67ee132d0dd10d91c2ab), if you don't have a fancy lwjgl editor in your launcher

I got it, but have a crash (ofc) and this is the log:
[`logs`](https://gist.github.com/mintyleaf/3319b9c8e4cec75c4013945bf7d7e799)
Particularly, this one fail:
`[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 2):
Vertex attribute Normal(4) is missing from the vertex descriptor.`

I know pretty much nothing about "vulkanizing" stuff, just found out that "kind of" issue [`there`](https://github.com/KhronosGroup/MoltenVK/discussions/1349)   
This is the first issue with actual proper crash report on macOSx64 there, and I'm ready to test it, if you want to move on with x64 Mac support

**Comment by AKeen12344** [comment]
Don't know why the readme doesn't say this, but macOS doesn't natively have Vulkan capability. Only OpenGL up to v4.1 and Metal are supported. This is why you are getting that error. 

Doing the same thing this project is doing but with Metal instead is likely out of bounds here. Also check out https://vulkan.lunarg.com/doc/sdk/latest/mac/getting_started.html because that's why I said natively.

**Comment by mintyleaf** [comment]
> Don't know why the readme doesn't say this, but macOS doesn't natively have Vulkan capability. Only OpenGL up to v4.1 and Metal are supported. This is why you are getting that error.
> 
> Doing the same thing this project is doing but with Metal instead is likely out of bounds here. Also check out https://vulkan.lunarg.com/doc/sdk/latest/mac/getting_started.html because that's why I said natively.

I have metal support by gpu, and successfully doing some gamedev with Godot 4 which is using Vulkan by default, and, it performing on my hd520 a lot better, than GL applications
So I tried give a shot to this mod =D

**Comment by xCollateral** [comment]
Did you download macOS version?

**Comment by Naterjack** [comment]
@mintyleaf Have you tried the new version (0.2.0 build 2)?
On the new build I cannot recreate your crash on either of two different Macs (one with dedicated Amd GPU and one with Intel Iris Plus 655).

**Comment by xCollateral** [comment]
I'll close it, if it still happens let me know.
