### ISSUE TITLE
missing library

### ISSUE THREAD

**Issue by SalvdorD21** [xCollateral/VulkanMod#170]
I get a crash message with "Failed to locate library: libvulkan.1.dylib"

**Comment by ezamelczyk** [comment]
Same on mac. Does this mod use MoltenVK?

**Comment by lockieluke** [comment]
+1 doesn't work on M1 for me

**Comment by ezamelczyk** [comment]
#192 fixes this. I'm just waiting for @xCollateral to merge it.

**Comment by xCollateral** [comment]
If you are on MacOS you have to download the MacOS version from Modrint: https://modrinth.com/mod/vulkanmod/versions
