### ISSUE TITLE
[1.19.3] Journeymap mixin issue. 

### ISSUE THREAD

**Issue by mysticdrew** [xCollateral/VulkanMod#174]
Looks like you are fully rewriting this method. 
https://github.com/xCollateral/VulkanMod/blob/edf26c7888800b2d795767d12cb383409361e10b/src/main/java/net/vulkanmod/mixin/debug/DebugHudM.java#L80
You do not really need to rewrite the whole method. 

I had a user report a crash when JM and Vulcan are together, details and crash report are here. 
https://github.com/TeamJM/journeymap/issues/547

This is my mixin inject point in that method. 
```
    @Inject(method = "drawGameInformation(Lcom/mojang/blaze3d/vertex/PoseStack;)V",
            at = @At(value = "INVOKE", target = "Ljava/util/List;add(Ljava/lang/Object;)Z",
                    shift = At.Shift.AFTER,
                    ordinal = 2),
            locals = LocalCapture.CAPTURE_FAILSOFT)
```

**Comment by mysticdrew** [comment]
Looking at your mixin, instead of rewriting the whole method, you could add two injections. 
Between the `list.add("For help: press F3 + Q");` and the for loop. And another at the end of the method. This would fix the compatibility issue.

**Comment by xCollateral** [comment]
Some time ago i managed to get journeymap running, but there were some issues with textures due to direct use of GlStateManager class. In order to reach full compatibility an interface for emulating OpenGL textures in Vulkan will be needed, unless journeymap rewrites all its texture handling to use higher level classes.

**Comment by mysticdrew** [comment]
> Some time ago i managed to get journeymap running, but there were some issues with textures due to direct use of GlStateManager class. In order to reach full compatibility an interface for emulating OpenGL textures in Vulkan will be needed, unless journeymap rewrites all its texture handling to use higher level classes.

I know, I made a lot of changes for you so we could get it working. But, with the current mixin issue, it wont even load. Overwriting methods with mixins will cause issues with other mods too. It should be avoided at all costs if possible.

**Comment by mysticdrew** [comment]
This should be resolved
