### ISSUE TITLE
Vanilla shaders try to use opengl

### ISSUE THREAD

**Issue by tr7zw** [xCollateral/VulkanMod#18]
![grafik](https://user-images.githubusercontent.com/5133936/168160191-30ab468f-a6e1-4532-8c4e-bbef3915820c.png)
Trying to spectate for example a creeper triggers a load of vanilla opengl shaders and with that a crash.

**Comment by The-Minecraft-Scientist** [comment]
Could you post the whole crash report?

**Comment by The-Minecraft-Scientist** [comment]
I haven't checked the vanilla client code, but it appears there's no mixin/override for the `GameRenderer.LoadShader` method

**Comment by xCollateral** [comment]
PostPass effects are working now.
