### ISSUE TITLE
Compatibility with Customizable Player Models

### ISSUE THREAD

**Issue by BaiTian6641** [xCollateral/VulkanMod#183]
I install both CustomPlayerModels and VulkanMod, and the player model display is a totally black model and some GUI is broken.

The Minecraft version is 1.19.3, the CustomPlayerModels version is 0.6.5a, the VulkanMod version is 0.2.1, the fabric version is 0.14.13, and the fabric API version is 0.73.2.

The mod author of the Customizable Player Models reports the Vulkan mod is missing RenderSystem.enableScissor, and DynamicTexture.setPixels implementation. See this link: https://github.com/tom5454/CustomPlayerModels/issues/369

![2023-02-04_01 33 56](https://user-images.githubusercontent.com/16750326/216780227-6b6e781f-bc40-49ce-990f-30683d1e7a6d.png)
![2023-02-04_01 20 16](https://user-images.githubusercontent.com/16750326/216780233-931065ce-117e-41e0-adbb-5bb0961b888f.png)
![2023-02-04_01 30 42](https://user-images.githubusercontent.com/16750326/216780235-8d2ee682-e6eb-4dd7-9e11-b92150503a28.png)

**Comment by netcore10** [comment]
Specifically, https://github.com/tom5454/CustomPlayerModels/issues/369#issuecomment-1416773777
