### ISSUE TITLE
Some transparent blocks have black outline when viewed from far away (mipmap issue)

### ISSUE THREAD

**Issue by Yr1t** [xCollateral/VulkanMod#2]
Mod Version: 0.1.1+2
Platform: Windows 11
GPU: AMD RX 5700 XT
Driver Version: 22.3.1

What it should look like:
![unknown](https://user-images.githubusercontent.com/60280919/163691484-1397cce3-ae87-4eac-ad01-33e8a960594e.png)

What it looks like:
![deez](https://user-images.githubusercontent.com/60280919/163691496-ff90f855-7023-4e81-bbee-f32d5679f840.png)

The arm is also stretched out when you increase your FOV, which I assume is known at this point.
Can people on other GPUs and OSes verify this? Not sure if this is something to do with my drivers or anything like that.

**Comment by Yr1t** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/60280919/163723998-539a3c34-c395-47f6-8f33-e292464064c6.png">
Turning mipmaps off fixes the black shrubs.

What it looks like now:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60280919/163724091-f97c0d03-19e1-4582-9c27-5822326b4d65.png">

I also figured out that this affects most textures with transparent elements (cactus also shows black outline in hotbar)
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/60280919/163724659-6b96a776-6671-45ff-a793-7611edff75f5.png">

**Comment by xCollateral** [comment]
New release fixed this issue.
