### ISSUE TITLE
Crash when world is finished loading

### ISSUE THREAD

**Issue by tomhag2005** [xCollateral/VulkanMod#20]
When the fabric API jar is located in the mods folder this error occurs where the game crashes. This does not happen without the API in the mods folder. The error was while tessellating a stone block and it said something about arraycopy and how the index was out of range

**Comment by BayuLewis** [comment]
According to your info, you should be able to use the FabricAPI by set  `always-tesselate-blocks=false` in `config/fabric/indigo-renderer.properties`. Mentioned in the Discord server, Collateral found a solution for this. Further info is that you can run other `mods`, but don't run `mods` that use `OpenGL call` which is not compatible with `VulkanMod` at the moment.
