### ISSUE TITLE
Crash when Rendering Chunks

### ISSUE THREAD

**Issue by muhammedesadcomert** [xCollateral/VulkanMod#201]
### Description

I encountered a crash while the game rendering a chunk.

### Steps to Reproduce

I am not sure what caused the error. It happened during regular gameplay while rendering a chunk.

### Mod List

- Fabric API (0.75.1+1.19.3)
- Vulkan Renderer (1.19.3-0.2.3)

### Crash log

https://mclo.gs/Vv5EFx9

**Comment by xCollateral** [comment]
That is a not enough memory error, try lowering render distance

**Comment by muhammedesadcomert** [comment]
I double-checked the logs and only 2.2 GB was used of the 6 GB allocated memory. How is memory not enough?

**Comment by muhammedesadcomert** [comment]
@xCollateral  I double-checked the logs and only 2.2 GB was used of the 6 GB allocated memory. How is memory not enough?
You can see it here:
![image](https://user-images.githubusercontent.com/46245749/227277404-d919ca1e-289c-45fe-b31a-e6d973f027dd.png)
