### ISSUE TITLE
Blocks below y=0 do not render when traveling between dimensions

### ISSUE THREAD

**Issue by NtimesN-2** [xCollateral/VulkanMod#202]
To replicate, travel from the nether to the overworld. Blocks below y=0 will not render, and traveling below y=0 will stop all blocks from rendering, including those above y=0.

Tested on Minecraft 1.19.3, mod version 0.2.3.

![image](https://user-images.githubusercontent.com/75134198/226131268-e5c17df0-0076-4d38-89cd-32c946650c78.png)

**Comment by xCollateral** [comment]
It should be fixed now.
