### ISSUE TITLE
Impossible to load certain world

### ISSUE THREAD

**Issue by Lolothepro** [xCollateral/VulkanMod#205]
[crash-2023-03-25_14.51.04-client.txt](https://github.com/xCollateral/VulkanMod/files/11069050/crash-2023-03-25_14.51.04-client.txt)
[latest.log](https://github.com/xCollateral/VulkanMod/files/11069051/latest.log)

**Comment by nm17** [comment]
Can you upload the world that it crashes in?

**Comment by Lolothepro** [comment]
https://ufile.io/tgvk876d

**Comment by Lolothepro** [comment]
fixed
