### ISSUE TITLE
Glowing effect don't work

### ISSUE THREAD

**Issue by ZiQu-dev** [xCollateral/VulkanMod#212]
Glowing effect (the outline from the effect) on entities from spectral arrows or giving an effect via commands doesn't show, but the particles from entities are showing without a problem.
![2023-04-05_20 21 59](https://user-images.githubusercontent.com/75249449/230170984-55ca113b-b517-47b3-bd9b-3539542af77f.png)

**Comment by thr3343** [comment]
This is a known issue afaik with the Glowing Lines/Specific shader used for the Glowing effect, which from the perspective of the game code IIRC is complicated to use and apply, so for simplicity its currently disabled.

(In Short Glowing is disabled by design as its difficult to work with)

**Comment by ZiQu-dev** [comment]
Oh okay, tahnk's for an info

**Comment by ZiQu-dev** [comment]
Oh okay, thank's for an info
