### ISSUE TITLE
[Enhancement] Add a shader compilation notice

### ISSUE THREAD

**Issue by Splarkszter** [xCollateral/VulkanMod#214]
You know, vulkan common thing compiling shaders on the background.

Add a notice so people don't freak out viewing their FPS go down and their CPU is at 100% usage.

I experienced it myself here on Linux with steam/proton so i rapidly figured out what it means when i saw that what happened on minecraft using this mod for the first time; so i'm pretty sure it is that, since now i get the normal 200FPS+ i get on this potato with this mod.

##Possibly Compiling Shaders:

<details>
  <summary>When standing still</summary>
  <img src="https://user-images.githubusercontent.com/90066319/230801282-7134af48-07f4-445b-9f15-6f3cbd79ad43.png">
</details>

<details>
  <summary>When loading chunks:</summary>
  <img src="https://user-images.githubusercontent.com/90066319/230801328-9583cc65-e99a-4f19-8eef-36309876aee2.png">
</details>

##Finished Compiling Shaders:
<details>
  <summary>Now when standing still:</summary>
  <img src="https://user-images.githubusercontent.com/90066319/230801385-c17d2024-d240-48a1-912d-74ee63ff11e1.png">
</details>

<details>
  <summary>Now when loading chunks:</summary>
  <img src="https://user-images.githubusercontent.com/90066319/230801438-4139ef03-7983-4ca5-8aec-4b8c51a7e19a.png">
</details>

**Comment by Splarkszter** [comment]
##Possibly Compiling Shaders:
![image](https://user-images.githubusercontent.com/90066319/230801282-7134af48-07f4-445b-9f15-6f3cbd79ad43.png)
When Loading Chunks:
![image](https://user-images.githubusercontent.com/90066319/230801328-9583cc65-e99a-4f19-8eef-36309876aee2.png)

##Finished Compiling Shaders:
![image](https://user-images.githubusercontent.com/90066319/230801385-c17d2024-d240-48a1-912d-74ee63ff11e1.png)
Now When Loading Chunks:
![image](https://user-images.githubusercontent.com/90066319/230801438-4139ef03-7983-4ca5-8aec-4b8c51a7e19a.png)

**Comment by Splarkszter** [comment]
Update: Added images to the original message and made it a bit fancier.

**Comment by Splarkszter** [comment]
Notes:
- I tested it multiple times and i get the exact same behaviour, i'm able to reproduce it. So yes, it's very probably Vulkan shader compilation.
- I'm using Linux Mint, The thing that displays performance is called MangoHUD
- Minecraft Launcher: Prism
- Java Version: Open-jdk 17

**Comment by xCollateral** [comment]
Pipeline/Shader creation does cause some stutter but it's very limited. I think the stuttering you are experiencing comes from chunk sections uploads.

**Comment by thr3343** [comment]
As xCollateral mentioned, shader stutter is a nonissue, as this mod only uses about 50 shaders to handle Minecraft itself, with most of them (about 30+) are compiled and loaded at the red Mojang splash screen before even entering the world which takes less than a second to compile.

_(Most of the actual lag is from DataFixerUpper being stupid and maxing out the CPU at 100%, which is a seperate issue and fixable using LazyDFU)_

ShaderC is used to compile the shaders, which is very fast and IIRC only takes at most about 50ms per shader.

And once a shader is loaded, it is only compiled once and never compiled again, so shutter should be virtually nonexistent

However i use an old 2014 i7 4790K with a GTX 1080Ti, which is very old, but may still compile the shaders much faster than other people's setups.

**Comment by thr3343** [comment]
Howver on the other hand, a Shader Compilation notice is a very good idea imho if heaver shaders (e.g. Shaderpacks) are ever used in the future, as ATM shaders are not currently reloaded with F3+T afaik as VulkanMod doesn't have full control over the Shader System Mojang uses atm.

**Comment by Splarkszter** [comment]
Hmmm... i'll try by installing all the optimization mods that i commonly use and that at least don't crash the game when used along vulkan(because who knows if they are active or unactive), on a fresh instance to see the the behavior exists specially while having LazyDFU active.

If i remember correctly, the instace on the issue report only had vulkanMod installed so that could be a thing, but the strange thing is that it only happened the first time the game bootted up. I'll test regardless, I'll be back.

**Comment by Splarkszter** [comment]
Ok, i didn't even need to test much, yeah, it's probably DFU what causes my issue if you said so, i had no issues when having at least LazyDFU, and worked fine.

<details>
  <summary>Mod List:</summary>
  <img src="https://user-images.githubusercontent.com/90066319/233204024-409de411-a3be-4558-b864-101162d01b4c.png">
</details>

Game loads usually in less than 35 seconds

<details>
  <summary>While first loading game:</summary>
  <img src="https://user-images.githubusercontent.com/90066319/233202060-c92118e1-7792-41e1-b78f-c63d193d58b8.png">
</details>

<details>
  <summary>First joining world (Before was 20-26FPS):</summary>
  <img src="https://user-images.githubusercontent.com/90066319/233204963-7046a358-9b41-43b9-aabe-12b10df55662.png">
</details>

**Comment by thr3343** [comment]
Its not your fault for getting confused, as I thought it was shader compilation as well several months ago, however this mod does seem to have abnormally bad issues with Initial Loading lag as DFU normally isn't this extreme/bad in most cases outside of super heavy modpacks. (Which isn't helped by slow ChunK Rebuilding/Uploading)

I still think having a much better shader management system with Compilation notices is a good idea,
as we only mostly get away with it ATM due to how cheap the default Core shaders are to compile using ShaderC as they are tiny compared to many shader packs.

However Shader compile lag will definately become a problem when/if this mod becomes able to support custom shaders, so your suggestion is still very valid and relevant in my opinion.
