### ISSUE TITLE
[Suggestion] Make the macOS version source code available to view

### ISSUE THREAD

**Issue by mrjasonn** [xCollateral/VulkanMod#216]
Please make the macOS version source code available to view.

**Comment by piemanau** [comment]
Its exactly the same but with the mac native as far as I know. They don't include them all as the mac natives are double the size of the windows and linux ones combined.

**Comment by piemanau** [comment]
For 0.3 the shader files are ever so slightly different and also have the macos natives, apart from that they are the exact same
