### ISSUE TITLE
[Compatibility] Make compatible with Minecraft 1.19.4

### ISSUE THREAD

**Issue by mrjasonn** [xCollateral/VulkanMod#217]
Please make this mod compatible with Minecraft 1.19.4.

**Comment by NXTler** [comment]
Works fine on my end, could you specify your issue?

**Comment by wb1016** [comment]
please close the issue

**Comment by mrjasonn** [comment]
Why did no one or me get around to closing this... Done (also the support for 1.19.4 was added a long time ago)
