### ISSUE TITLE
Minecraft crashing loading the game

### ISSUE THREAD

**Issue by Myuui** [xCollateral/VulkanMod#218]
https://mclo.gs/pDo8vj6

**Comment by Splarkszter** [comment]
Nothing that relies on OpenGL API will work on Vulkan. If you want support, ask the maintainers of that mod to add support for the Vulkan rendering API.

Same goes with everything rendering related, Vulkan is new so support and work is needed and it will be gradual, but Vulkan is the future.

Also just make sure your GPU supports the lastest version of Vulkan, update your drivers.

**Comment by thr3343** [comment]
After looking at the log, the GPU failed to intialise when loading the mod. VulkanMod only needs a minimum of Vulkan 1.1, and the GPU used [does support Vulkan 1.3](https://www.techpowerup.com/gpu-specs/uhd-graphics-24eu-mobile.c3484), So currently suspect an outdated Intel GPU Driver, as the version seems to be a 2021 driver.

Am not an expert with this so apologies if the above isn't helpful.

**Comment by Myuui** [comment]
i've updated my graphics card driver to 27.20.100.9664 i hope it works

![screenshot](https://media.discordapp.net/attachments/594815387917352962/1097267348278362122/image.png)

**Comment by Myuui** [comment]
> i've updated my graphics card driver to 27.20.100.9664 i hope it works
> 
> ![screenshot](https://camo.githubusercontent.com/623e65414dbdb4d5927e3ceff1c1aea5f74f4518baaff2a0120b5dcdae8897f4/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3539343831353338373931373335323936322f313039373236373334383237383336323132322f696d6167652e706e67)

**Success!**
But the performance is worse than Sodium sadly
1.19.4 Singleplayer *bad* screenshot

![pic](https://media.discordapp.net/attachments/594815387917352962/1097282332043518104/IMG_20230417_000137.jpg?width=668&height=501)

**Comment by Splarkszter** [comment]
>  But the performance is worse than Sodium sadly

Make sure to wait until shader compilation finishes if your cores are at 100%

Other thing is, do not test just raw fps, test while moving and while having things that actually affect performance, like mobs, trees, chunk rendering, etc.

**Comment by thr3343** [comment]
Mentioned this in another issue, but imo is strongly recommended to use [LazyDFU](https://www.curseforge.com/minecraft/mc-mods/lazydfu), as it is used to make developing with this mod easier, and least imo VulkanMod works best with it.

it dosen remove all of the CPu and Chunk ReBuild lag, but completely elimiates the CPU from being maxed out at 100% when loading the game.

AFAIk shaders are not the issue as most of them (30+) are compiled when the Red Splash Screen appears and take less than a second using ShaderC to compile them

Some specific Chunk/Entity rendering shaders are also compiled at certain events in game, but only about 50+ shaders are used in game, and they usually take about 50ms or less each, and are always reused once created so are never recompiled.

AFAIK, shader Compilation/Stuttering issues are usually sudden lag spike stalls (i.e. Elden Ring Bugs IIRC), and not consistent, constant lag like this, which points to a different bottleneck elsewhere.

**Comment by Myuui** [comment]
Do you know other **Minecraft performance mods** compatible with **Vulkan**?

**Comment by Zorklis** [comment]
Try updating everything to the latest?
