### ISSUE TITLE
Scissor effect doesn't work with text rendering

### ISSUE THREAD

**Issue by isXander** [xCollateral/VulkanMod#220]
![javaw_fr3owEBPml](https://user-images.githubusercontent.com/43245524/231757372-cedb6730-a123-4161-a318-efb47298e69c.png)

**Comment by Felix14-v2** [comment]
> ![javaw_fr3owEBPml](https://user-images.githubusercontent.com/43245524/231757372-cedb6730-a123-4161-a318-efb47298e69c.png)

Isn't this a cloth-config bug?

**Comment by xCollateral** [comment]
It should be fixed.
