### ISSUE TITLE
VERY slow chunk loading and rebuild times

### ISSUE THREAD

**Issue by christopher317** [xCollateral/VulkanMod#221]
i have no idea why but for some reason, before i switched to this mod, my performance in terms of chunk loading was excellent ( sodium + iris ), but when using this mod, chunks loaded 3x or more slowly, and the only other thing i changed was the world gen mods i was using. 

also, sometimes the chunk mesh builder freezes and im not sure why ( at least i think that's whats going on )
https://user-images.githubusercontent.com/86526198/232226716-85cadec8-98f7-4ad5-aa44-bbe5481853dc.mp4

this is how drastically different the loading times where ( exact same mods other than the ones listed above the clips )
literally 2x longer

when using sodium ( and iris ):
https://user-images.githubusercontent.com/86526198/231903613-3420c861-24fa-466d-8731-16083319776d.mp4

when using vulkan mod:
https://user-images.githubusercontent.com/86526198/231904707-9a382173-5b7a-4221-9410-fecdd5557c92.mp4

logs:
sodium + iris: [latest.log](https://github.com/xCollateral/VulkanMod/files/11227273/latest.log)
vulkan mod: [latest.log](https://github.com/xCollateral/VulkanMod/files/11227272/latest.log)

also in my experience this persists long after loading into a world.

**Comment by Splarkszter** [comment]
if your CPU is a toaster it will struggle as long as the vulkan shaders are being compiled, just wait with the game/world open until your CPU it's no longer at 100% usage. that would mean you are good to go.

**Comment by Splarkszter** [comment]
if the problem persists, an alternative is installing the standard c2me... very efficient chunk management engine, as far as my testing goes, compatible with vulkan since it doesn't touch graphical rendering.

**Comment by thr3343** [comment]
_(IMHO, it is strongly suggested to use [LazyDFU](https://www.curseforge.com/minecraft/mc-mods/lazydfu), massively helps to reduce the stupid 100% CPU issue, and imo VulkanMod works best with it.)_

This is a currently known Performance bug where the Chunk geometry is extremely slow to Transfer into the GPU, which is not a new bug and has been a nuscence since at least VulkanMod 1.18.2 IIRC.

AFAIk ideas are being experimented with to help fix the Chunk lag once and for all, 
but VulkanMod dosen't have a massive team unlike Sodium, so making any progress on optimising chunk reloads will take a good amount of time.

**Comment by christopher317** [comment]
> if your CPU is a toaster it will struggle as long as the vulkan shaders are being compiled, just wait with the game/world open until your CPU it's no longer at 100% usage. that would mean you are good to go.

i saw another issue that was about adding a notification for when that finishes, after seeing that issue thats what i thought was going on.
edit: what thr3343 appears to be whats going on, compilation finishes about 20-40 seconds after loading into a world, tho it isnt as bad as it was when compiling.

> if the problem persists, an alternative is installing the standard c2me... very efficient chunk management engine, as far as my testing goes, compatible with vulkan since it doesn't touch graphical rendering.

was already using c2me.


> _(IMHO, it is strongly suggested to use [LazyDFU](https://www.curseforge.com/minecraft/mc-mods/lazydfu), massively helps to reduce the stupid 100% CPU issue, and imo VulkanMod works best with it.)_

il try using LazyDFU if i can figure out why its crashing after updating Linux and changing nothing about the instance.
edit: figured that out, driver issue.

> This is a currently known Performance bug where the Chunk geometry is extremely slow to Transfer into the GPU, which is not a new bug and has been a nuscence since at least VulkanMod 1.18.2 IIRC.
> 
> AFAIk ideas are being experimented with to help fix the Chunk lag once and for all, but VulkanMod dosen't have a massive team unlike Sodium, so making any progress on optimising chunk reloads will take a good amount of time.

even tho its probably going to take a long time for it to be fixed its nice to know that this is a known issue that is being worked on :)

**Comment by christopher317** [comment]
> You may also consider using graalvm ee

never heard of it but sounds like a good idea, defiantly going to try.

**Comment by xCollateral** [comment]
It improved on latest versions.
