### ISSUE TITLE
Hi may I ask does Vulkan for minecraft need Vulkan api

### ISSUE THREAD

**Issue by Sleepyhuai** [xCollateral/VulkanMod#225]
Hi may I ask does Vulkan for minecraft need Vulkan api

**Comment by thr3343** [comment]
VulkanMod definately needs the Vulkan API to function, however this is typically included in your GPU driver, so you don't need to do anything or install any addons/programs as its already there.

So as long as your GPU/Driver isn't ancient and supports a minimum of Vulkan 1.1(2018), it should be able to use this mod AFAIK.
