### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by leominerwork** [xCollateral/VulkanMod#235]
I have no mods
GPU: AMD Radeon R7 240
Minecraft: 1.19.3
Fabric: 0.14.19
VulkanMod: 0.2.3
[latest.log](https://github.com/xCollateral/VulkanMod/files/11380445/latest.log)

**Comment by Zorklis** [comment]
Try updating fabric api and vulkan and check back

**Comment by xCollateral** [comment]
Same as #233
