### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by PUSHok100** [xCollateral/VulkanMod#237]
minecraft 1.19.4 crashes on startup
[hs_err_pid4580.log](https://github.com/xCollateral/VulkanMod/files/11414344/hs_err_pid4580.log)
gpu: amd radeon rx 580
vulkan mod 0.2.5

**Comment by Zorklis** [comment]
Check incompatible mod list, update your vulkan and minecraft. and if still crashes provide crash report

**Comment by xCollateral** [comment]
I'll close this since it happened on a very old version. Try latest version.
