### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by FireBirdWas** [xCollateral/VulkanMod#238]
Log:
[latest.log](https://github.com/xCollateral/VulkanMod/files/11415431/latest.log)
GPU: GEFORCE GTX 1650 laptop
Vulkan mod version: 0.2.3
No other mods used

**Comment by wb1016** [comment]
'no other mods used'
but log says ```info: [17:56:24] [main/INFO]: Loading 102 mods:```
it is mod conflict. please close the issue.

**Comment by Zorklis** [comment]
Yeah not sure why you lied about no other mods being used. Like wb1016 said, this should be closed. Pretty self explanatory, check compatible mod list
Clearly you have incompatible mods, dashloader, cloth config (maybe)

**Comment by FireBirdWas** [comment]
I did a mistake and did not sent the right log, but i changed pc and removed some mods and it works now
