### ISSUE TITLE
No MacOS version

### ISSUE THREAD

**Issue by someoneignorable** [xCollateral/VulkanMod#244]
There is no MacOS version available on modrinth

**Comment by roworu** [comment]
https://modrinth.com/mod/vulkanmod-macos

**Comment by piemanau** [comment]
Now in the main jar

**Comment by thr3343** [comment]
TBH it might be worth removing  the Macos version from modrinth, as it seem to be causing confusion 
(we've been noticing this misconception/confusion in the discord as well)

The Macos build is also now completely outdated; its included in the main jar as of 0.3.4 iirc
