### ISSUE TITLE
Invisible lava.

### ISSUE THREAD

**Issue by queuejw** [xCollateral/VulkanMod#246]
I went into the mine and died in it because the lava was invisible. 

![2023-05-27_09 26 53](https://github.com/xCollateral/VulkanMod/assets/120617193/62f52fd3-ad55-44b6-8f48-b5056f888eac)
![2023-05-27_09 27 38](https://github.com/xCollateral/VulkanMod/assets/120617193/4bec64d7-1474-4bc6-a079-d780c0e8b533)
![2023-05-27_09 26 41](https://github.com/xCollateral/VulkanMod/assets/120617193/28b491b4-c3fb-4bba-8d6e-30116e167d61)
![2023-05-27_09 35 03](https://github.com/xCollateral/VulkanMod/assets/120617193/de627c38-468e-4bc5-95be-819f3886f7cb)

**Comment by thr3343** [comment]
The broken/missing lava texture was fixed in a 0.3.1 hotfix iirc, its just not on github atm

**Comment by xCollateral** [comment]
Fixed.
