### ISSUE TITLE
Both iris and optifabric cannot use this plugin to report an error, the latest fabric

### ISSUE THREAD

**Issue by lizheyo77** [xCollateral/VulkanMod#25]
Both iris and optifabric cannot use this plugin to report an error, the latest fabric

**Comment by BayuLewis** [comment]
It's not compatible with Iris and Optifabric. To be more specefic, mods that use OpenGL call is not compatible AT ALL at the moment and it will crash the game. Remember this is still pre-alpha.

**Comment by Felix14-v2** [comment]
> To be more specefic, mods that use OpenGL call is not compatible AT ALL at the moment and it will crash the game

That is, if Sodium is rewritten to use Vulkan, it is theoretically possible to get the benefits of VulkanMod and the Sodium Engine optimization at the same time?

**Comment by andreasdc** [comment]
> > To be more specefic, mods that use OpenGL call is not compatible AT ALL at the moment and it will crash the game
> 
> That is, if Sodium is rewritten to use Vulkan, it is theoretically possible to get the benefits of VulkanMod and the Sodium Engine optimization at the same time?

Could be and I think that would be nice.

**Comment by err2ror** [comment]
yeah but it would be thaousands of hours of work to redo
i dont think sodium devs have the courage to do it again
