### ISSUE TITLE
MacOS version For 1.20/1.20.1?

### ISSUE THREAD

**Issue by IsuckAtcomputering** [xCollateral/VulkanMod#261]
I would like to know when it will come out

**Comment by someoneignorable** [comment]
search vulkan MacOs on modrinth

**Comment by Abadodod** [comment]
the macos version is in a separate link
https://modrinth.com/mod/vulkanmod-macos

**Comment by IsuckAtcomputering** [comment]
ok

**Comment by IsuckAtcomputering** [comment]
go ahead and close it
