### ISSUE TITLE
VkInstance in LWJGL not found (!?)

### ISSUE THREAD

**Issue by terraquad** [xCollateral/VulkanMod#265]
I am having a problem launching Minecraft with Vulkan Mod.
After I parsed the crash, I was quite shocked that VkInstance couldn't be found by VulkanMod (Path: org.lwjgl.vulkan.VkInstance)
It also crashes without any other mods installed, so the error is either in VulkanMod or in LWJGL.

Here's the crash dump (from the instance with my other mods): 
[crash-2023-07-10_12.55.54-client.txt](https://github.com/xCollateral/VulkanMod/files/12001117/crash-2023-07-10_12.55.54-client.txt)

The modpack I use:
[Repro Crash Build.zip](https://github.com/xCollateral/VulkanMod/files/12001198/Repro.Crash.Build.zip)

Minimal reproduction modpack crash dump:
[crash-2023-07-10_13.13.05-client.txt](https://github.com/xCollateral/VulkanMod/files/12001220/crash-2023-07-10_13.13.05-client.txt)

PC Specs:
 - CPU: AMD Ryzen 7 5800H
 - GPU: NVIDIA GeForce RTX 3060
 - RAM: 16 GB
 - SSD Space: 1 TB

Minecraft (related) specs:
 - Version: 1.19.4
 - Mod Version: 0.3.2 (from Modrinth)
 - Fabric API Version: QFAPI 6.0.0 (from Modrinth)
 - Mod Loader: Quilt 0.19.2
 - LWJGL Version: 3.3.1
 - MC Launcher: Prism Launcher 7.1

**Comment by terraquad** [comment]
I've done some more investigating and I think it's one of these three issues:
 - QFAPI (Quilted Fabric API): May not support all functionality of Fabric API
 - LWJGL: For some reason the class cannot be loaded, maybe due to JAR corruption which is unlikely but possible
 - The mod itself: Wrong import path (which is very unlikely due to it working on other computers) or issues with my setup.

**Comment by itsTyrion** [comment]
- unlikely
- the mod includes it
- yes and no - it appears it's not compatible with Quilt. I switched to Fabric and it worked (after a few rounds of crashing and removing mods)

**Comment by xCollateral** [comment]
It seems quilt loader isn't able to load external libraries correctly, it's not solvable from the mod's side. Use fabric loader until it gets fixed.
