### ISSUE TITLE
Blocks stop rendering at Y=<0

### ISSUE THREAD

**Issue by ikunat33** [xCollateral/VulkanMod#266]
From above areas below Y=0 look like black bottomless pits with no walls.
If I go below Y=0 I can see the blocks above that point but not if a block that is below Y=0, which is not rendered, is in the way.
I can still interact with the invisible blocks and an outline of the selected block is formed.
This sometimes happens as soon as the game is loaded, sometimes it takes a while, It can persist across reloads but saving the game while below Y=0, exiting Minecraft, then reloading the game seems to fix the issue.. at least this is the first time I have tried it and that was the result.

My system:
ROG Strix G15
AMD Ryzen 7 6800H with Radeon Graphics × 8
16GB RAM
NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile]

Linux Mint 21 64 bit
GDLauncher 1.1.30
Minecraft version 1.20.1
Fabric modloader 0.14.21
VulcanMod 1.20.1_0.3.2
(no other mods)

**Comment by xCollateral** [comment]
It should be fixed.
