### ISSUE TITLE
License on Curseforge is wrong

### ISSUE THREAD

**Issue by SuperStormer** [xCollateral/VulkanMod#278]
It's tagged as "All Rights Reserved" on CF, even though the [LICENSE](https://github.com/xCollateral/VulkanMod/blob/1.19.2/LICENSE) file says it's LGPL.

**Comment by SuperStormer** [comment]
related issue: 1.19.4 branch is missing a LICENSE file.

**Comment by xCollateral** [comment]
I don't think that's related to the code or the Github project.
