### ISSUE TITLE
Game crashes while in world

### ISSUE THREAD

**Issue by artdeell** [xCollateral/VulkanMod#29]
Game crashes sooner or later (usually sooner) after entering the world.
[crash-2022-06-10_15.20.03-client.txt](https://github.com/xCollateral/VulkanMod/files/8880172/crash-2022-06-10_15.20.03-client.txt)
GPU: Adreno 650 with Vulkan 1.1.128, mod was patched to work with LWJGL 3.2.3

**Comment by Zorklis** [comment]
Still happening on the latest?

**Comment by xCollateral** [comment]
The error `VK_ERROR_DEVICE_LOST = -4` is too generic, validation layers' debug info would be needed. Anyway we don't support Android devices, at least for the time being.
