### ISSUE TITLE
Vulkan prioritises Integrated Graphics GPU over Dedicated GPU

### ISSUE THREAD

**Issue by ansientmc** [xCollateral/VulkanMod#296]
When I use Vulkan on 1.20.1, despite having a gpu that supports Vulkan Rendering it immediately goes to my integrated graphics GPU

**Comment by Andarwinux** [comment]
https://github.com/xCollateral/VulkanMod/blob/1.20.1/src/main/java/net/vulkanmod/vulkan/Device.java#L41-L103

**Comment by xCollateral** [comment]
It will prioritise Dedicated GPUs now. We even added a GPU selector in the settings screen to manually select the device used.
