### ISSUE TITLE
Game crashes completely at random

### ISSUE THREAD

**Issue by artdeell** [xCollateral/VulkanMod#30]
Game randomly crashes, when browsing in-game menus or when entering the world.
[crash-2022-06-10_15.10.58-client.txt](https://github.com/xCollateral/VulkanMod/files/8880293/crash-2022-06-10_15.10.58-client.txt)
GPU: Adreno 630

**Comment by RoxyCN** [comment]
> Game randomly crashes, when browsing in-game menus or when entering the world. [crash-2022-06-10_15.10.58-client.txt](https://github.com/xCollateral/VulkanMod/files/8880293/crash-2022-06-10_15.10.58-client.txt) GPU: Adreno 630

Maybe you can try Pojavlauncher to run Minecraft on Android device,I already succeed
My GPU:Adreno 660
![-b2c5729762c6239](https://user-images.githubusercontent.com/91813030/183602583-5fd8de25-517e-4594-81aa-15cea9f2470c.jpg)

**Comment by Zorklis** [comment]
Did you try on the latest Vulkan?

**Comment by xCollateral** [comment]
Same as #29
