### ISSUE TITLE
Incompatible with yet another config lib v3

### ISSUE THREAD

**Issue by Josh65-2201** [xCollateral/VulkanMod#303]
## Description
Uncertain if it the only one causing the issue as it the only one shown in the log

## Logs
[crash-2023-09-19_16.40.41.9985-quilt_loader.txt](https://github.com/xCollateral/VulkanMod/files/12663946/crash-2023-09-19_16.40.41.9985-quilt_loader.txt)

## Versions
Minecraft: 1.20.1
Quilt: 0.20.2
Mod: 0.3.2

**Comment by Zorklis** [comment]
You're playing with incompatible mods like Iris, sodium. Check compatible mods list, remove incompatible , update mods and Vulkan to latest and test again.

**Comment by xCollateral** [comment]
Quilt is not compatible for now, use Fabric.
