### ISSUE TITLE
Crashes on launch "EXCEPTION_ACCESS_VIOLATION"

### ISSUE THREAD

**Issue by ASOwnerYT** [xCollateral/VulkanMod#313]
https://mclo.gs/XnSpWnC

**Comment by Zorklis** [comment]
Sodium is not supported. Also indium is useless..
I think cloth-config is crash-y
ImmediatelyFast is your crash reason.

**Comment by xCollateral** [comment]
Try using latest version and check if you are using [incompatible mods](https://github.com/xCollateral/VulkanMod/wiki/Incompatible-mods).

**Comment by ASOwnerYT** [comment]
> Sodium is not supported. Also indium is useless.. I think cloth-config is crash-y ImmediatelyFast is your crash reason.

Those mods (except cloth-config) were disabled, you can see in the logs

**Comment by Felix14-v2** [comment]
Are you still able to reproduce the issue with the newest VulkanMod version?
