### ISSUE TITLE
Crash while using Neat mod

### ISSUE THREAD

**Issue by Morizera** [xCollateral/VulkanMod#318]
Running a fabric server 1.20.1

Game crashs after joining and trying to run a bit inside a village.
Crash log:
https://mclo.gs/w6RI8l3

**Comment by Zorklis** [comment]
It says: 
"at **vazkii**._neat_.HealthBarRenderer.hookRender(HealthBarRenderer.java:270)"
seems like you are using [Vazkii](https://modrinth.com/user/Vazkii)'s [neat](https://modrinth.com/mod/neat): Neat 1.20-35-FABRIC ; mod which seems to be incompatible/causes the crash.

**Comment by thr3343** [comment]
> It says: "at **vazkii**._neat_.HealthBarRenderer.hookRender(HealthBarRenderer.java:270)" seems like you are using [Vazkii](https://modrinth.com/user/Vazkii)'s [neat](https://modrinth.com/mod/neat): Neat 1.20-35-FABRIC ; mod which seems to be incompatible/causes the crash.

We hook directly into HealthBarRenderer, so this looks like another Mixin conflict

Mixin conflicts are by far the most common mod incompatibility
Ironically alot of compat issues have nothing do with Vulkan at all, as crazy as it sounds

**Comment by xCollateral** [comment]
It has been fixed.
