### ISSUE TITLE
Crash at game initialization `Mixin transformation of net.minecraft.class_309 failed`

### ISSUE THREAD

**Issue by headquarter8302** [xCollateral/VulkanMod#319]
Log:
[crash-2023-10-27_21.00.29-client.txt](https://github.com/xCollateral/VulkanMod/files/13194075/crash-2023-10-27_21.00.29-client.txt)
* OS: Windows 10 22H2
* GPU: NVIDIA MX230
* Driver version: 31.0.15.3742

No other mods are installed, not even Fabric API, and no, the lack of Fabric API does not contribute to the crash

**Comment by xCollateral** [comment]
You are using wrong mod version. Use 1.20.2 for Minecraft 1.20.2
