### ISSUE TITLE
Please allow compatibility with Create

### ISSUE THREAD

**Issue by elpideus** [xCollateral/VulkanMod#321]
Create is one of the most popular new mods out there so it would be nice for it to be compatible with VulkanMod.

**Comment by homogoblin28** [comment]
I may be wrong but I don't think the creator of VulkanMod can do anything. Create most likely makes calls to OpenGL which won't work, ask Create for compatibility instead.

**Comment by elpideus** [comment]
> I may be wrong but I don't think the creator of VulkanMod can do anything. Create most likely makes calls to OpenGL which won't work, ask Create for compatibility instead.

Okay, thank you very much!

**Comment by elpideus** [comment]
> I may be wrong but I don't think the creator of VulkanMod can do anything. Create most likely makes calls to OpenGL which won't work, ask Create for compatibility instead.

Okay, thank you very much!
