### ISSUE TITLE
Item rendering bug

### ISSUE THREAD

**Issue by Inverted-Fin** [xCollateral/VulkanMod#326]
![3a5c3faded05f740c9a51aa769d0f5db](https://github.com/xCollateral/VulkanMod/assets/134783108/9584dae0-b138-4e75-add6-1066265ad531)
![4c0bcbcac810512a0980d25d9d9b5888](https://github.com/xCollateral/VulkanMod/assets/134783108/eb49609c-8442-44cd-bdbc-906f0ebd8106)
![635aa549e5eec80e519f82b24cc233be](https://github.com/xCollateral/VulkanMod/assets/134783108/c4eec16b-1785-44a6-8807-0c917a4b4981)
![847586e0ea1a53b7253cd000c3ec765a](https://github.com/xCollateral/VulkanMod/assets/134783108/5abd8dc0-ba59-40a1-915a-f8b27cf03d51)
![c3ae802da7ffa8eb0a53415878122cd9](https://github.com/xCollateral/VulkanMod/assets/134783108/c9fed2e3-6a02-49fb-b362-429d5128e3c1)

vulkan mod version(arm64 patch):VulkanMod_1.20.1-0.3.4_v5_arm64_-imagelessFrameBuffers

As you can see，these are can't normally render out items(discovered):
1.shield
2.chest and ender chest
3.a variety of colors shulker box
4.a variety of colors bed
5.a variety of colors flag

**Comment by Inverted-Fin** [comment]
need fix!

**Comment by Inverted-Fin** [comment]
And a variety of colors sign board

**Comment by xCollateral** [comment]
It should be fixed.
