### ISSUE TITLE
[Crash] Game crashes upon startup on Linux

### ISSUE THREAD

**Issue by APie357** [xCollateral/VulkanMod#331]
The game window pops up for a split second and then disappears.
Logs: https://mclo.gs/hPEauiu

CPU: AMD Ryzen 7 7700X
GPU: Nvidia RTX 3060
OS: Arch Linux (linux-6.6.2-arch1-1)
Desktop: i3wm
Display Server: X11
Loader: Quilt

**Comment by NXTler** [comment]
VulkanMod only supports the Fabric launcher. Linux is not the issue here.

**Comment by APie357** [comment]
Changing the loader to fabric worked. Thank you!
