### ISSUE TITLE
Broken window border

### ISSUE THREAD

**Issue by Xyphyn** [xCollateral/VulkanMod#336]
![image](https://github.com/xCollateral/VulkanMod/assets/80978739/640633ba-5186-462a-a992-2f25e6efac5b)

In Arch Linux, in any window size other than the launch size, a duplicate window bodrer of the old border is visible.

The window border also has no decorations.

```
# System Details Report
---

## Report details
- **Date generated:**                              2023-12-04 17:55:09

## Hardware Information:
- **Processor:**                                   AMD Ryzen™ 5 5600X × 12
- **Graphics:**                                    AMD Radeon RX 6600 XT

## Software Information:
- **OS Name:**                                     Arch Linux
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.9-arch2-1
```

**Comment by ghost** [comment]
Same issue seen on Nobara Linux.

![image](https://github.com/xCollateral/VulkanMod/assets/123809052/c7971f26-53f2-4164-9195-c19e19a37f5b)


> ## Hardware Information:
> - **Processor:**                                   AMD Ryzen™ 7 5800X × 16
> - **Graphics:**                                    AMD Radeon™ RX 6800
> 
> ## Software Information:
> - **OS Name:**                                     Nobara Linux 38 (Thirty Eight)
> - **GNOME Version:**                               44.2
> - **Windowing System:**                            Wayland
> - **Kernel Version:**                              Linux 6.6.7-203.fsync.fc38.x86_64

**Comment by Enderteck** [comment]
Same problem here :

![Screenshot](https://github.com/xCollateral/VulkanMod/assets/123917079/5d8983c0-8371-462e-9542-d95297da1893)

Fedora 39 Intel core i5 RTX 3060 mobile on wayland

**Comment by ghost** [comment]
I have the same issue

**Comment by 0hStormy** [comment]
I have general issues with minecraft and wayland (waygl and vkmod) too

**Comment by xCollateral** [comment]
It should be fixed.
