### ISSUE TITLE
Bug with vines (Vulkan Mod 0.3.7)

### ISSUE THREAD

**Issue by MrOteex** [xCollateral/VulkanMod#342]
I was in a jungle biome when i found this bug, im 99% sure the vines are the ones causing this issue because i planted some jungle trees in another biome and it did occur when too much vines appeared, but when i start to remove the vines the bug progressively fixes, the more vines i break the less buggy it is.
![2023-12-12_16 28 07](https://github.com/xCollateral/VulkanMod/assets/153699936/7a5c5d77-a6be-4672-a921-b675b437ae1a)
![2023-12-11_19 50 39](https://github.com/xCollateral/VulkanMod/assets/153699936/f55efd02-feec-4c06-92bf-40e056a1ec22)
![2023-12-11_19 31 29](https://github.com/xCollateral/VulkanMod/assets/153699936/25de5c1a-b27c-4ef2-9eaa-cc8601f09e71)

**Comment by Felix14-v2** [comment]
Can you reproduce this without 3D vines resourcepack?

**Comment by MrOteex** [comment]
i tried it without 3d vines and it doesn't happen, i forgotten that i had that resource pack lol

**Comment by MrOteex** [comment]
i tested a bit more and got the same result with the 3d sugar cane, when a lot is rendered it bugs, but i guess is not a big deal

**Comment by xCollateral** [comment]
I don't think there's an issue with vines but rather seems chunk mesh corruption. It should be fixed on newer versions.
