### ISSUE TITLE
Broken textures of some blocks

### ISSUE THREAD

**Issue by PipeDruzhe** [xCollateral/VulkanMod#350]
When I just downloaded 0.3.9, everything was fine with textures, but after a while the textures broke (1.20.1)

No new mods have been added

![ToGitHub](https://github.com/xCollateral/VulkanMod/assets/154964872/fe937dd1-b619-4c3b-8f15-491e55e509eb)

**Comment by PipeDruzhe** [comment]
In the picture, I think, not all the broken blocks are here, there are blocks that I immediately noticed.

**Comment by NXTler** [comment]
Not an issue on my machine.

**Comment by Kai-Denzel-Jane** [comment]
This also seems to be an issue on my device too.

Blocks I've noticed are Copper Ore and a few others

**Comment by xCollateral** [comment]
I think this might be cause by an incompatibility Model Gap Fix that has been fixed on newer versions.

**Comment by PipeDruzhe** [comment]
Ok, Bro👍

пн, 16 сент. 2024 г., 15:26 xCollateral ***@***.***>:
