### ISSUE TITLE
arm64 device after joining server and used server custom resource pack.After,texture error

### ISSUE THREAD

**Issue by Inverted-Fin** [xCollateral/VulkanMod#354]
such as you see,after I used vulkan mod 0.3.7 arm64 patch,joined the server and used server custom pack.After texture rendering error.When I keep this error exit the server,rejoin server,still have this problem,and after,played single player,still have texture error.Later,I restart the game,after that,I enter single player,no problem(tip:Is restart game after),if I rejoin server and use server custom resouce pack,so,still have texture error,still need restart game.
![28D6CB3FD3834FC956A3C869D3D1818D](https://github.com/xCollateral/VulkanMod/assets/134783108/7ae9ca0b-ebe7-48bf-8c9e-0f41653bbcd8)

**Comment by Inverted-Fin** [comment]
![28D6CB3FD3834FC956A3C869D3D1818D](https://github.com/xCollateral/VulkanMod/assets/134783108/205fbf6e-1e95-488c-a7d8-d60ab7242ff2)

**Comment by Inverted-Fin** [comment]
vk mod version:0.3.7_Unoffical_arm64
gpu:adreno610(use system vulkan driver)

**Comment by Inverted-Fin** [comment]
need fix!This is very serious problem

**Comment by Felix14-v2** [comment]
Please, provide the game log and full launcher log. Also keep in mind that Android support is unofficial, so consider joining VulkanMod Discord to get help with that.

**Comment by Inverted-Fin** [comment]
[latestlog(1).txt](https://github.com/xCollateral/VulkanMod/files/13919354/latestlog.1.txt)
this is lasest log

**Comment by xCollateral** [comment]
Pojav and Android devices launcher are not supported.
