### ISSUE TITLE
Don't crash when not compatible mod is detected

### ISSUE THREAD

**Issue by andreasdc** [xCollateral/VulkanMod#368]
A good idea would be to disable the uncompatible mods instead of crash, I don't remember the exact way it is right now.

**Comment by Poopooracoocoo** [comment]
I think #323 is a better approach

**Comment by andreasdc** [comment]
This way you could run it with every mod, but they would be disabled, after startup you can have info about the disabled mods.

**Comment by Zorklis** [comment]
I understand it would be easier to use (no need to delete/move mods) and it would be provide incompatible mods, but incompatibility needs to be testing and even though Minecraft is the most popular game ever it still lacks testers. That's my opinion, not a dev.

**Comment by xCollateral** [comment]
I concur with @Poopooracoocoo, if we want to go this route #323 is the only reasonable approach.

**Comment by andreasdc** [comment]
> I concur with @Poopooracoocoo, if we want to go this route #323 is the only reasonable approach.

meh
