### ISSUE TITLE
1.20/1.20.1 texture bug

### ISSUE THREAD

**Issue by TomXD1234** [xCollateral/VulkanMod#372]
1.20/1.20.1 chest shulker box and sings and many more are bugged but this problem doesn't seem in 1.20.2 here photo 
![Screenshot_2024_0207_093333_com discord](https://github.com/xCollateral/VulkanMod/assets/148317266/0a5dcb7c-eb68-4167-9de0-623fe6686d4d)
And many many more items glitch and shield also

**Comment by 0hStormy** [comment]
what version of vulkanmod are you running? And are you using pojav?

**Comment by TomXD1234** [comment]
> what version of vulkanmod are you running? And are you using pojav





Yes I'm using pojav and vulkan version 3.7 v14 patch vulkan and if I use 1.20.1 then this bug appear

**Comment by 0hStormy** [comment]
huh, I know 0.3.5 has a texture bug in general but I don't know what's going on here, also this isn't the place to ask for help with pojav stuff.

**Comment by N1zyx3** [comment]
> > какая версия вулканмода у вас установлена? И ты используешь pojav
> 
> Да, я использую pojav и vulkan версии 3.7 v14, патч vulkan, и если я использую 1.20.1, то появляется эта ошибка

Have you found a solution?

**Comment by xCollateral** [comment]
Pojav lanucher is not supported. Anyway this issue wasn't Android specific and affected every platform and it has been fixed.
