### ISSUE TITLE
idik why it crashes when launching

### ISSUE THREAD

**Issue by TraderTheWolf** [xCollateral/VulkanMod#377]
heres crash report:
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2024-02-16 16:43:40
Description: Initializing game

java.lang.IllegalStateException: No GLCapabilities instance set for the current thread. Possible solutions:
	a) Call GL.createCapabilities() after making a context current in the current thread.
	b) Call GL.setCapabilities() if a GLCapabilities instance already exists for the current context.
	at org.lwjgl.opengl.GL.checkCapabilities(GL.java:234)
	at org.lwjgl.opengl.GL.getCapabilities(GL.java:229)
	at net.minecraft.class_1008.method_4227(class_1008.java:131)
	at com.mojang.blaze3d.platform.GLX._init(GLX.java:106)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:852)
	at net.minecraft.class_310.<init>(class_310.java:505)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.opengl.GL.checkCapabilities(GL.java:234)
	at org.lwjgl.opengl.GL.getCapabilities(GL.java:229)
	at net.minecraft.class_1008.method_4227(class_1008.java:131)
	at com.mojang.blaze3d.platform.GLX._init(GLX.java:106)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:852)
	at net.minecraft.class_310.<init>(class_310.java:505)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Mac OS X (x86_64) version 13.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 266347216 bytes (254 MiB) / 570425344 bytes (544 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel Iris Plus Graphics 655
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x3ea5
	Graphics card #0 versionInfo: Revision ID: 0x0001
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 10240.00
	Virtual memory used (MB): 6135.45
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 626.00
	JVM Flags: 8 total; -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterfpsdist: Better FPS distance Mod 1.20.1-3.8
		betterpingdisplay: Better Ping Display 1.1.1
		boostedbrightness: Boosted Brightness 2.2.0
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cupboard: cupboard 1.20.1-1.5
		elementa: Elementa 619
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		essential: Essential 1.3.0.6+g4dc55a95bd
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		exordium: Exordium 1.1.3-mc1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		fabric-api: Fabric API 0.83.1+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
		fabricloader: Fabric Loader 0.14.22
		forgeconfigapiport: Forge Config API Port 8.0.0
		java: OpenJDK 64-Bit Server VM 17
		marlows-crystal-optimizer: Marlow's Crystal Optimizer 1.0.0
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.1.0
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
		nohurtcamplus: NoHurtCam+ 2.3.1-1.20.1
		org_jetbrains_annotations: annotations 13.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		puzzleslib: Puzzles Lib 8.0.0
		replaymod: Replay Mod 1.20.1-2.6.13
		simple-armor-hud: Simple armor hud 1.20.1-1.3.1
		skinswapper: Skin Swapper 3.1.4
			org_apache_httpcomponents_httpclient: httpclient 4.5.10
			org_apache_httpcomponents_httpcore: httpcore 4.4.12
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		stylisheffects: Stylish Effects 8.0.0
		taterzens: Taterzens 1.11.6
			config2brigadier: Config to Brigadier 1.2.5
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.0-rc.2+1.20-rc1
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
			sgui: sgui 1.2.2+1.20
		universalcraft: UniversalCraft 323
		vigilance: Vigilance 295
		vulkanmod: VulkanMod 0.3.2
			org_lwjgl_lwjgl-shaderc: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-macos: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-macos-arm64: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-vma: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-macos: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-macos-arm64: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vulkan: lwjgl-vulkan 3.3.2
			org_lwjgl_lwjgl-vulkan_natives-macos: lwjgl-vulkan 3.3.2
			org_lwjgl_lwjgl-vulkan_natives-macos-arm64: lwjgl-vulkan 3.3.2
	Launched Version: fabric-loader-0.14.22-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz

**Comment by NXTler** [comment]
Those are a lot of graphic mods you are trying to run with VulkanMod.
Essential and Exordium are definitely incompatible, everything else you will have to figure out yourself.

**Comment by Zorklis** [comment]
This should be closed, as @NXTler explained the problem (incompatible mods)
