### ISSUE TITLE
Cant Find Vulan Capable GPU

### ISSUE THREAD

**Issue by cm3k** [xCollateral/VulkanMod#38]
When I launch I get the following error
`java.lang.RuntimeException: Failed to find GPUs with Vulkan support`

I suspect that it is because in my system there is a high performance GPU and then the integrated graphics and it is choosing the integrated graphics.

Though I don't know why this would happen as Java is set to run on the High Performance GPU

**Comment by Titaniumtown** [comment]
What OS, drivers, and specs?

**Comment by xCollateral** [comment]
This shouldn't happen, Vulkan class will try to find a vulkan capable device among all devices. I suggest to check driver installation.

**Comment by Titaniumtown** [comment]
ah windows 💀

**Comment by cm3k** [comment]
> ah windows 💀

i am aware of what os i have installed

**Comment by xCollateral** [comment]
This issue should be fixed with newer builds, if not open a new issue.
