### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by ghost** [xCollateral/VulkanMod#384]
I play pojav launcher in newer update pojav launcher add support vulkan mod but i will enter with this mod game doesn't open just in black screen and don't work.
My device info: it name is xiaomi poco f5
Snapdragon 7+ gen 2
Vulkan version:1.1.128
Adreno 7xx

**Comment by boasbakker** [comment]
What the hell that is a mobile phone
Ah wow I didn't know PojavLauncher, that is cool.
But that's expected that it isn't supported lol

**Comment by Felix14-v2** [comment]
Please, read this https://github.com/xCollateral/VulkanMod/issues/391#issuecomment-2036774935

**Comment by ghost** [comment]
Oh okay . . . I use arm 64_v8a is not supported for this mod
