### ISSUE TITLE
incomptiable with advanced-framework

### ISSUE THREAD

**Issue by MetsukiMio** [xCollateral/VulkanMod#385]
![image](https://github.com/xCollateral/VulkanMod/assets/83895170/9545907e-4d34-4554-8394-3e2ca8a72788)
[minecraft-exported-logs-2024-03-07T18-57-02.log](https://github.com/xCollateral/VulkanMod/files/14522992/minecraft-exported-logs-2024-03-07T18-57-02.log)
Seems like shader file loading failed, I can't solve this issue

**Comment by NXTler** [comment]
Known incompatibility, can be closed.
