### ISSUE TITLE
some crash not sure what it means 

### ISSUE THREAD

**Issue by Shelly333-2** [xCollateral/VulkanMod#390]
[latest.log](https://github.com/xCollateral/VulkanMod/files/14817305/latest.log)
it crashes randomly maybe the log can help you fix the problem

**Comment by qwerty12356-wart** [comment]
Seems like your game crashed because you ran out of memory. How much memory did you allocate to minecraft?

**Comment by Shelly333-2** [comment]
my game has 4gb alocated this crash does not happen on sodium

**Comment by NXTler** [comment]
Could you provide a mod list? But yeah, it really looks like you are running out of ram or vram.

**Comment by xCollateral** [comment]
It seems a compatibility issue, if it still persists check incompatible list and/or create a new issue.
