### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by RelaxingNostalgia** [xCollateral/VulkanMod#391]
Error on PojavLauncher,crashes at game startup
Log:
[latestlog.txt](https://github.com/xCollateral/VulkanMod/files/14859933/latestlog.txt)

**Comment by Felix14-v2** [comment]
First of all, ARM32/64 support has been dropped due to some issues with PojavLauncher community. So you can't use VulkanMod anymore.
Secondly, you are using outdated version which is not supported anyways

**Comment by RelaxingNostalgia** [comment]
> First of all, ARM32/64 support has been dropped due to some issues with PojavLauncher community. So you can't use VulkanMod anymore. Secondly, you are using outdated version which is not supported anyways

1 actually i was able to vulkanmod in pojav but patched.

2 that version was downloaded from curseforge,and there was no specification in the description that it was no longer supported.

**Comment by Felix14-v2** [comment]
> that version was downloaded from curseforge,and there was no specification in the description that it was no longer supported

As long as you use outdated version, you have no support, because it is impossible to update version which already has been updated. If you want bug/crash fixes, use the newest version.

**Comment by NXTler** [comment]
This can be closed, you will not get support when using PojavLauncher.
