### ISSUE TITLE
Banner color is broken

### ISSUE THREAD

**Issue by Lolothepro** [xCollateral/VulkanMod#394]

**Comment by 0hStormy** [comment]
Example:
![2024-04-06_12 06 58](https://github.com/xCollateral/VulkanMod/assets/80485413/5c133af3-87e5-437b-b0ed-b812a69fc318)

**Comment by Slymeball** [comment]
Since #405 was just closed, I might as well put the +1 here as well.

> +1 to this
> 
> Minecraft 1.20.4 with VulkanMod 0.4.0 on Arch Linux x86-64 using NVIDIA 550.76
> 
> https://github.com/xCollateral/VulkanMod/assets/51765267/0fe3da70-ea1f-41a2-bbfd-03ad1ebd6088
> 
> And yes, this occurs with banners too. Same wrong colors as well!
> 
> ![image](https://github.com/xCollateral/VulkanMod/assets/51765267/4a986082-e44e-4887-b11f-416fafda4d38)
