### ISSUE TITLE
VulkanMod Crashes: java.lang.RuntimeException: Failed to create buffer:-2 or Failed to submit draw command buffer: -4 (1.20.4 with 0.4.0)

### ISSUE THREAD

**Issue by boasbakker** [xCollateral/VulkanMod#396]
Crash 1: https://paste.ee/p/8wRNq (-2)
Crash 2: https://paste.ee/p/Lu8wM (-2)
Crash 3: https://paste.ee/p/E5kC6 (-2)
Crash 4: Failed to create buffer:-2
Crash 5: https://paste.ee/p/Y620H also using MiniHud, java.lang.RuntimeException: Failed to submit draw command buffer: -4
Crash 6: https://paste.ee/p/yZcc3 (-2) (not using indirect draw, with the mods MiniHUD and ModMenu)
Crash 9: https://paste.ee/p/hKxio (not using indirect draw, no other mods)

Playing MC with 32 render distance, looking around. There was a lag spike and then the game crashed. 
It seems to happen more when the setting called 'Indirect Draw' is enabled. I did so because my CPU is always the bottleneck when playing Minecraft. 
Software: Windows 10, Java 17
Hardware: i3-10105F, GTX 1050, 2-8 GB RAM allocated of the 32GB total
1.9/2GB VRAM usage most of the time. 
Apart from this performance is great (140fps) with rd=32 so far

**Comment by boasbakker** [comment]
With dev version also -2 crash within a minute of enabling the setting. https://paste.ee/p/o7qlw

**Comment by boasbakker** [comment]
Also had a crash with the dev version without the setting enabled. https://paste.ee/p/8EYPO

**Comment by boasbakker** [comment]
No crashes with rd=24

**Comment by xCollateral** [comment]
The -2 error stands for `VK_ERROR_OUT_OF_DEVICE_MEMORY`, which implies the application run out of VRAM. The -4 error is more generic error, but highly likely might be caused by the same issue.
This is not a support forum, anyway try lowering your `Render Distance` setting.

**Comment by boasbakker** [comment]
> The -2 error stands for `VK_ERROR_OUT_OF_DEVICE_MEMORY`, which implies the application run out of VRAM. The -4 error is more generic error, but highly likely might be caused by the same issue. This is not a support forum, anyway try lowering your `Render Distance` setting.

I didn't create this issue for support. I created it because this is a bug, Minecraft shouldn't crash, even with high render distance.
