### ISSUE TITLE
java.lang.RuntimeException: Failed to create instance on AMD R5 1600 + RX 580 with Prism Launcher in Arch Linux

### ISSUE THREAD

**Issue by yigitsalar** [xCollateral/VulkanMod#399]
Crash log: [crash-2024-04-07_15.13.09-client.txt](https://github.com/xCollateral/VulkanMod/files/14897116/crash-2024-04-07_15.13.09-client.txt)
Using VulkanMod 0.4.0 with Fabric 0.15.7 without any other mods.
`vulkaninfo` output: [vulkaninfo.log](https://github.com/xCollateral/VulkanMod/files/14897122/vulkaninfo.log)
Game window appears and after a second or two, it disappears.

**Comment by leominerxd** [comment]
Do you have amdvlk installed?

**Comment by xCollateral** [comment]
There's an issue on Vulkan instance creation. It seems not resolvable on our side, try updating your driver.
