### ISSUE TITLE
-13 Device connection lost error on AMD (Mesa) / Linux

### ISSUE THREAD

**Issue by polarbub** [xCollateral/VulkanMod#4]
Not found by me, found by Lavender#1458 on discord. 

Might work with proprietary AMD drivers on linux. Hasn't been tested.

RX 560
Manjaro

Crash log
https://pastebin.com/MhMGb6HA

Relates to #1

**Comment by BayuLewis** [comment]
To get around this mod work on Linux
1. Go to https://github.com/google/shaderc and download the Linux build.
2.  Inside the .zip file go to `/install/lib/ take the libshaderc_shared.so.1` extract it to somewhere and rename it to `shaderc.so`
3. After that go to `/tmp/lwjgl.../3.2.2-SNAPSHOT/` create `libwindows` folder and keep creating until you created like this `/tmp/lwjglbayu/3.2.2-SNAPSHOT/libwindows/x64/org/lwjgl/shaderc/` after that pull the `shaderc.so` file into the `shaderc` folder
4. Go to `https://www.lwjgl.org/browse/release/3.2.2/linux/x64` and download  liblwjgl.so and then put it into `/tmp/lwjg.../3.2.2-SNAPSHOT/`
I think this should fix the error you're having, let me know if you're still having trouble.

**Comment by polarbub** [comment]
This fixed this issue for the user on discord.
