### ISSUE TITLE
Render distance not updating

### ISSUE THREAD

**Issue by leominerxd** [xCollateral/VulkanMod#402]
OS: Windows 11 x64
CPU: Ryzen 3 1200
GPU: AMD Radeon R7 240 (Displayed as R5 240)
Java: Oracle JDK 17

https://mclo.gs/cyJk7Oj

**Comment by leominerxd** [comment]
Closing: Conflicting mod - ServerCore

**Comment by Dashy22** [comment]
mine is doing this without server core
