### ISSUE TITLE
Problem when I leave a game.

### ISSUE THREAD

**Issue by Xphalnos** [xCollateral/VulkanMod#404]
When I start a game with the mod (0.4.0) and quit, it happens to me. it didn't do that with the old version (0.3.9).
![image](https://github.com/xCollateral/VulkanMod/assets/164882787/9418251a-9ac5-4abe-a771-6debb4d930f4)

OS: Windows 11 23H2
GPU: Intel UHD Graphics (with latest drivers)
CPU: Intel Pentium Gold 8505
Game version: 1.20.4

Log : [latest.log](https://github.com/xCollateral/VulkanMod/files/14934010/latest.log)

**Comment by xCollateral** [comment]
It should be fixed by a0e6c2d
