### ISSUE TITLE
Wrong Colours

### ISSUE THREAD

**Issue by PINKeHamton** [xCollateral/VulkanMod#405]
banner and sheep colours are wrong pink is purple that`s the only think I see

**Comment by Slymeball** [comment]
+1 to this

Minecraft 1.20.4 with VulkanMod 0.4.0 on Arch Linux x86-64 using NVIDIA 550.76

https://github.com/xCollateral/VulkanMod/assets/51765267/0fe3da70-ea1f-41a2-bbfd-03ad1ebd6088

And yes, this occurs with banners too. Same wrong colors as well!

![image](https://github.com/xCollateral/VulkanMod/assets/51765267/4a986082-e44e-4887-b11f-416fafda4d38)

**Comment by PINKeHamton** [comment]
Minecraft 1.20.4 with VulkanMod 0.4.0 on Arch Linux using NVIDIA Drivers (can`t remeber the numbers i have a GTX 770 ) but i was getting different colours i wonder if its a VK 1.2 problem

**Comment by PINKeHamton** [comment]
on NVIDIA Drivers ill try nouveau drivers latter when i have time and wayland as well ill dump logs

**Comment by Slymeball** [comment]
> **@PINKeHamton said:**
> (can`t remeber the numbers i have a GTX 770)

You can check in the F3 menu in MC or by running `nvidia-smi` in the shell and noting the driver version at the top.
Chances are, if you're on Arch and keeping your system up to date, you're running 550.76.

**Comment by xCollateral** [comment]
Duplicate of #394
