### ISSUE TITLE
Lithium + VulkanMod causes Rendering bug

### ISSUE THREAD

**Issue by timdevorg** [xCollateral/VulkanMod#406]
Using VulkanMod in combination with Lithium causes any face that is adjacent to a farmland block to be transparent, eg:

![2024-04-20_14 37 48](https://github.com/xCollateral/VulkanMod/assets/42376598/71c60bbe-d2d9-41ed-a45b-af1d926c8067)
![2024-04-20_14 37 53](https://github.com/xCollateral/VulkanMod/assets/42376598/b62af197-989c-49bb-bb2c-cac0e207c533)

Without Lithium, this does not happen (so yes, it is **not** VulkanMod's fault) and seems to be a **compatibility issue**.

Maybe it's related to this line in the logs?
```
[14:37:28] [main/WARN]: Method overwrite conflict for method_10153 in vulkanmod.mixins.json:chunk.DirectionMixin from mod vulkanmod, previously written by me.jellysquid.mods.lithium.mixin.math.fast_util.DirectionMixin. Skipping method.
```

Either way, the full log is attatched. 
[latest.log](https://github.com/xCollateral/VulkanMod/files/15048244/latest.log)

Cheers.

**Comment by xCollateral** [comment]
Commit 863c6da should have fixed this issue.
