### ISSUE TITLE
Block Model and hitbox is missaligned

### ISSUE THREAD

**Issue by Enderteck** [xCollateral/VulkanMod#407]
Here are pictures of it happening:

![Minecraft Screenshot 8](https://github.com/xCollateral/VulkanMod/assets/123917079/5681ec69-3eda-4bb6-98f9-2089f38e2db7)
![Minecraft Screenshot 7](https://github.com/xCollateral/VulkanMod/assets/123917079/5cbf201d-7eb6-4120-966d-e36c8e22dd38)
![Minecraft Screenshot 6](https://github.com/xCollateral/VulkanMod/assets/123917079/891cf49b-ef17-453f-85a4-6686a2b1f312)
![Minecraft Screenshot 5](https://github.com/xCollateral/VulkanMod/assets/123917079/3300225d-3960-4fb1-8b39-8e9dcdbf1500)
![Minecraft Screenshot 4](https://github.com/xCollateral/VulkanMod/assets/123917079/c58f9c63-00b9-480c-baf3-e84073e341cf)
![Minecraft Screenshot 3](https://github.com/xCollateral/VulkanMod/assets/123917079/2629ff63-a26b-4bd7-87ce-73cd44a9f056)
![Minecraft Screenshot 2](https://github.com/xCollateral/VulkanMod/assets/123917079/50705e43-0158-4ee3-93df-9a8d077e9d6a)
![Minecraft Screenshot 1](https://github.com/xCollateral/VulkanMod/assets/123917079/34e3736a-e28b-4f21-ba2b-19358f49afa7)

There are no texturepacks.

Here's my mod list:

  [✔] BetterF3-9.0.2-Fabric-1.20.4
  [✔] Jade-1.20.4-fabric-13.3.1
  [✔] MouseTweaks-fabric-mc1.20-2.26
  [✔] PresenceFootsteps-1.11.3
  [✔] RoughlyEnoughItems-14.1.714-fabric
  [✔] SmoothScrollingRefurbished+1.20.4-1.1.2
  [✔] VulkanMod_1.20.4-0.4.0
  [✔] accurate-block-placement-1.2.1
  [✔] architectury-11.1.17-fabric
  [✔] cloth-config-13.0.121-fabric
  [✔] entity_model_features_fabric_1.20.4-2.0
  [✔] entity_texture_features_fabric_1.20.4-6.0
  [✔] entityculling-fabric-1.6.4-mc1.20.4
  [✔] fabric-api-0.97.0+1.20.4
  [✔] fabric-language-kotlin-1.10.19+kotlin.1.9.23
  [✔] ferritecore-6.0.3-fabric
  [✔] lazydfu-0.1.3
  [✔] lithium-fabric-mc1.20.4-0.12.1
  [✔] memoryleakfix-fabric-1.17+-1.1.5
  [✔] modernfix-fabric-5.16.1+mc1.20.4
  [✔] modmenu-9.1.0-beta.1
  [✔] notenoughanimations-fabric-1.7.1-mc1.20.4
  [✔] skinlayers3d-fabric-1.6.2-mc1.20.4
  [✔] smoothgui-0.1.0
  [✔] smoothswapping-0.9.2-1.20.4-fabric
  [✔] tia-1.20-1.1-fabric
  [✔] worldedit-mod-7.3.0

**Comment by StonkDragon** [comment]
I had the same issue, removing lithium fixed it

**Comment by xCollateral** [comment]
If it was caused by lithium bug, it should be solved by 863c6da

**Comment by Enderteck** [comment]
Nice, thanks !
