### ISSUE TITLE
Rendering Block Entity Crash

### ISSUE THREAD

**Issue by FrostFizzie** [xCollateral/VulkanMod#409]
Version: 1.20.4-0.4.1

Mods: 
- Vulkan
- Authme

Environment: Fabric Dev

Max RAM: 32 GB
Unused Storage: 1.4TB 

Logs: 
[latest.log](https://github.com/xCollateral/VulkanMod/files/15140362/latest.log)

**Comment by xCollateral** [comment]
It's fixed.
