### ISSUE TITLE
Minihud light overlay rendering bug

### ISSUE THREAD

**Issue by CommanderDani** [xCollateral/VulkanMod#41]
Minihud light overlays turn yellow and show a lot of strange behaviors when using vulkanmod for rendering. Watch the video attached below.

https://drive.google.com/file/d/1bpBpnrrDMwuXIeWPX7k1aKItl_4JGcjC/view?usp=sharing

Supposed to look like this:
![image](https://user-images.githubusercontent.com/87468791/175566410-365e4379-e48d-4453-a1f4-cc43c0cd4078.png)

Specs: Intel i7-6700
Intel HD Graphics 530
32gb RAM
Mod version: VulkanMod_1.18.2-0.1.5+1

**Comment by CommanderDani** [comment]
Specs: Intel i7-6700
Intel HD Graphics 530
32gb RAM
Vulkan version: VulkanMod_1.18.2-0.1.5+1

**Comment by xCollateral** [comment]
It should be solved.
