### ISSUE TITLE
Server Rendering problems

### ISSUE THREAD

**Issue by Enderteck** [xCollateral/VulkanMod#410]
I've played with the mod with no issue in Solo and I just wanted to play on hypixel with this amazing performance.
But, on Hypixel, it looks like the game render stuff upside down ?

The pause menu is also invisible in this state, so disconnection isn't always easy.

Once I loaded in this is what I get:

![Screenshot 1](https://github.com/xCollateral/VulkanMod/assets/123917079/f72a2aa9-0fcf-463c-a7e4-a174294c1c3d)
![Screenshot 4](https://github.com/xCollateral/VulkanMod/assets/123917079/b4271996-5e70-4887-85a5-fabdd17fc010)
![Screenshot 7](https://github.com/xCollateral/VulkanMod/assets/123917079/b6bb7ecb-5aee-43d7-89ff-f956137be144)

The weirdest thing is that exept from only having this issue in multiplayer, looking at a map looks fixes the problem as long as you look at it.

![Screenshot 8](https://github.com/xCollateral/VulkanMod/assets/123917079/7b38cedc-fcd9-48c0-a516-785fb70f5c17)

Here's the log:

https://mclo.gs/HgYtLSZ

And the mod list I used:

- accurateblockplacement 1.2.1
	- architectury 11.1.17
	- betterf3 9.0.2
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- entity_model_features 2.0.1
	- entity_texture_features 6.0.1
	   \-- org_apache_httpcomponents_httpmime [4](https://mclo.gs/HgYtLSZ#L4).5.10
	- entityculling 1.6.4
	- fabric-api 0.97.0+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.[5](https://mclo.gs/HgYtLSZ#L5)0+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e221[6](https://mclo.gs/HgYtLSZ#L6)cb4f
	   |-- fabric-block-view-api-v2 1.0.5+[7](https://mclo.gs/HgYtLSZ#L7)8d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+7[8](https://mclo.gs/HgYtLSZ#L8)d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d7[9](https://mclo.gs/HgYtLSZ#L9)8af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.87+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
	   |-- fabric-dimensions-v1 2.1.62+78d798af4f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.[10](https://mclo.gs/HgYtLSZ#L10)+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.1.0+dba[11](https://mclo.gs/HgYtLSZ#L11)95c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.21+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.5+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.[12](https://mclo.gs/HgYtLSZ#L12)+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- ferritecore 6.0.3
	- jade [13](https://mclo.gs/HgYtLSZ#L13).3.1
	- java 17
	- lazydfu 0.1.3
	- lithium 0.12.1
	- memoryleakfix 1.1.5
	- minecraft 1.20.4
	- modernfix 5.17.0+mc1.20.4
	- modmenu 9.2.0-beta.2
	- mousetweaks 2.26
	- notenoughanimations 1.7.2
	- presencefootsteps 1.11.3
	   \-- kirin 1.17.1+1.20.4
	- roughlyenoughitems [14](https://mclo.gs/HgYtLSZ#L14).1.720
	   \-- error_notifier 1.0.9
	- skinlayers3d 1.6.3
	- smoothgui 0.1.0
	- smoothscrollingrefurbished 1.1.2
	- smoothswapping 0.9.2
	- tia 1.20-1.1
	- vulkanmod 0.4.1
	   |-- org_lwjgl_lwjgl-shaderc 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vma 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan_natives-macos 3.3.2
	   \-- org_lwjgl_lwjgl-vulkan_natives-macos-arm64 3.3.2
	- worldedit 7.3.0+6678-55745ad

**Comment by XuanXue2008** [comment]
It seemed like that the same reason to cause this problem.

**Comment by ThatMG393** [comment]
It's caused by the glowing effect, the dev knows about this so expect a fix soon

**Comment by xCollateral** [comment]
I confirm it is caused by post pass glowing effect #411
