### ISSUE TITLE
Glowing effect bug

### ISSUE THREAD

**Issue by XuanXue2008** [xCollateral/VulkanMod#411]
![image](https://github.com/xCollateral/VulkanMod/assets/138149926/afd6dc56-5736-46cc-990d-ac6ea7032194)

**Comment by NXTler** [comment]
What is the issue? Could you translate it?

**Comment by XuanXue2008** [comment]
Too many entities causing rendering errors.
In the case of too many entities, rendering errors occur, resulting in this situation.
I'm poor in English ,so I use the machine translation. :(

**Comment by NXTler** [comment]
No problem, the translation turned out just fine. Thanks for reporting this! This error could also be caused by the glowing effect. Could you try to replicate this issue without glowing entities?

**Comment by XuanXue2008** [comment]
okay,i will try.
please wait for a moment. : )

**Comment by XuanXue2008** [comment]
hey I  have tired again. I used the copy carpet machine to make a lot of entities.It seems that this problem is not caused by the entities.

**Comment by XuanXue2008** [comment]
It could cause by the Beacon lights.

**Comment by Enderteck** [comment]
Looks to be the same issue that I got

https://github.com/xCollateral/VulkanMod/issues/410

**Comment by XuanXue2008** [comment]
Do you have some way to slove this problem?

**Comment by XuanXue2008** [comment]
:(
I think mojang should do some work on vulkan.

**Comment by thr3343** [comment]
Does this bug occur in 0.4.1?
At least to my current knowledge, this should have been fixed in 0.4.0.

**Comment by XuanXue2008** [comment]
yes,I use the latest version.

**Comment by XuanXue2008** [comment]
It caused by theglowing effect.
sorry, I made a mistake.   :(   😭

**Comment by XuanXue2008** [comment]
![image](https://github.com/xCollateral/VulkanMod/assets/138149926/cd3173d7-79f7-43f4-9fe3-e485b409fd50)
