### ISSUE TITLE
Glow status effect broken rendering

### ISSUE THREAD

**Issue by Mukunya** [xCollateral/VulkanMod#419]
## Hardware:
AMD Ryzen 7 5800X
NVidia RTX 4060

## Software:
Manjaro
Nvidia 550.78 proprietary driver
Vulkan 1.3.277
Vulkanmod 0.4.1 on fabric 1.15.11-1.20.4 (no other mods)

## Issue:
To reproduce, look at any mob with the glow status effect. 

![Screenshot from 2024-05-18 10-43-47](https://github.com/xCollateral/VulkanMod/assets/51750827/ad3b5069-9e5a-4686-9566-5f66e7222e60)

**Comment by lv37** [comment]
This was already fixed in https://github.com/xCollateral/VulkanMod/commit/ef64206bdd48b09358612637b4b3adfed3ec5c45
