### ISSUE TITLE
Not working on Pop_OS!

### ISSUE THREAD

**Issue by FirstMelody** [xCollateral/VulkanMod#42]
The windows just shown up and crashed few seconds later.

Distro:Pop_OS
Nvidia Driver:515.48.07
MInecraft 1.18.2
LWJGL 3.3.1
Fabric 0.14.8

[10:05:12] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[10:05:16] [Render thread/INFO]: Narrator library successfully loaded
[10:05:19] [Render thread/INFO]: Reloading ResourceManager: Default
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Serial number of failed request:  242
  Current serial number in output stream:  250
Process exited with code 1.

**Comment by MOVZX** [comment]
I can confirm that it's working very good under GNU/Linux.

Installed using Lutris.

![image](https://user-images.githubusercontent.com/3374397/176335954-6e98ee05-9f61-491e-b893-5f8d6eee4cd5.png)

![Screenshot_20220629_090630](https://user-images.githubusercontent.com/3374397/176335826-c4dec66b-cf42-4b9e-b962-bbf722f5af9b.png)

[tlauncher_06_29_2022_09_05_04.log](https://github.com/xCollateral/VulkanMod/files/9006681/tlauncher_06_29_2022_09_05_04.log)

**Comment by FirstMelody** [comment]
> 

I mean it cannot run property under Linux natively. Compatibility tool will cause performance loss. It is meaningless to use this mod to increase fps as 1.18.2 fabric runs faster natively.

**Comment by FirstMelody** [comment]
> I can confirm that it's working very good under GNU/Linux.
> 
> Installed using Lutris.
> 
> ![image](https://user-images.githubusercontent.com/3374397/176335954-6e98ee05-9f61-491e-b893-5f8d6eee4cd5.png)
> 
> ![Screenshot_20220629_090630](https://user-images.githubusercontent.com/3374397/176335826-c4dec66b-cf42-4b9e-b962-bbf722f5af9b.png)
> 
> [tlauncher_06_29_2022_09_05_04.log](https://github.com/xCollateral/VulkanMod/files/9006681/tlauncher_06_29_2022_09_05_04.log)

Differ

**Comment by FirstMelody** [comment]
> I can confirm that it's working very good under GNU/Linux.
> 
> Installed using Lutris.
> 
> ![image](https://user-images.githubusercontent.com/3374397/176335954-6e98ee05-9f61-491e-b893-5f8d6eee4cd5.png)
> 
> ![Screenshot_20220629_090630](https://user-images.githubusercontent.com/3374397/176335826-c4dec66b-cf42-4b9e-b962-bbf722f5af9b.png)
> 
> [tlauncher_06_29_2022_09_05_04.log](https://github.com/xCollateral/VulkanMod/files/9006681/tlauncher_06_29_2022_09_05_04.log)

Different distro may perform differently.
And hardware difference also will decide if the issue happens.
More information will be pleased

**Comment by MOVZX** [comment]
Here's my PC info:

movzx@Dominator:~$ inxi -SCG
System:
  Host: Dominator Kernel: 5.18.7-darkness-ryzen-minimal x86_64 bits: 64
    Desktop: KDE Plasma 5.24.4 Distro: Ubuntu 22.04 LTS (Jammy Jellyfish)
CPU:
  Info: 16-core model: AMD Ryzen 9 5950X bits: 64 type: MT MCP cache:
    L2: 8 MiB
  Speed (MHz): avg: 3605 min/max: 2200/5083 cores: 1: 3598 2: 3598 3: 3591
    4: 3596 5: 3594 6: 3598 7: 3594 8: 3686 9: 3605 10: 3599 11: 3596 12: 3599
    13: 3655 14: 3599 15: 3597 16: 3589 17: 3594 18: 3598 19: 3609 20: 3589
    21: 3597 22: 3597 23: 3597 24: 3597 25: 3597 26: 3587 27: 3599 28: 3599
    29: 3592 30: 3601 31: 3736 32: 3606
Graphics:
  Device-1: NVIDIA GA104 [GeForce RTX 3070 Lite Hash Rate] driver: nvidia
    v: 515.48.07
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    gpu: nvidia resolution: 2560x1440~144Hz
  OpenGL: renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.48.07
movzx@Dominator:~$

**Comment by xCollateral** [comment]
I tested it and it's working now.
