### ISSUE TITLE
Can't switch to other Window using Windows Key (In Fullscreen)

### ISSUE THREAD

**Issue by AtomSnow** [xCollateral/VulkanMod#43]
![image](https://user-images.githubusercontent.com/51972322/175944874-a6b91bcc-a146-46ae-9427-11a95eda588f.png)
 It just doesn't work

**Comment by oknacupZero** [comment]
Can confirm, it just freezes the screen when i try to alt tab.

**Comment by JAB-dev** [comment]
Yeah the fullscreen should be changed to some sort of borlesswindow mode

**Comment by xCollateral** [comment]
It seems to be a bug with Vulkan API itself. New versions support borderless window.
