### ISSUE TITLE
Cannot use resource packs

### ISSUE THREAD

**Issue by Furina-imw** [xCollateral/VulkanMod#434]
Hello! i am having trouble with using resource packs on vulkan mod. Any package I installed into the game either failed to load the terrain or had texture errors. and here is an example  when I install the package "glow ore" 
![Screenshot_20240620-132558](https://github.com/xCollateral/VulkanMod/assets/89261608/36d54705-8030-4af1-b963-0d399b499e9b)

**Comment by trnahuman** [comment]
Pojavlauncher not offical supported al of pojavlauncher forks have malware risk or maybe spyware

**Comment by Felix14-v2** [comment]
Anyways, Continuity [is](https://github.com/xCollateral/VulkanMod/discussions/226#:~:text=Continuity) in the incompatible mods list, so glowing ore resourcepack shouldn't work as well
