### ISSUE TITLE
0.4.3 Requires Minecraft 1.20.4 or 1.20.3

### ISSUE THREAD

**Issue by leominerxd** [xCollateral/VulkanMod#437]
Logs: https://pastebin.com/E5GaBNys

PC Configuration:
CPU: Ryzen 5 3400G
iGPU: Radeon Vega 11
OS: Fedora Linux 40

**Comment by NXTler** [comment]
The log says what's going on:
`- Mod 'VulkanMod' (vulkanmod) 0.4.3 requires version 1.20.3 or version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.6!`
It's intended behavior.

**Comment by leominerxd** [comment]
according to the changelogs it should have support up to 1.21, but both 1.21 and 1.20.6 won't work with it

**Comment by NXTler** [comment]
Did you downloaded the correct one on https://modrinth.com/mod/vulkanmod/versions ?

**Comment by leominerxd** [comment]
yes

**Comment by NXTler** [comment]
But there is no 1.20.6 version for 0.4.3. Only a 1.21 version, which is another file.

**Comment by xCollateral** [comment]
0.4.3 does not support Minecraft 1.20.6

**Comment by leominerxd** [comment]
but what about 1.21 not working too

**Comment by NXTler** [comment]
Choose the correct version and it will work. We don't have a "one file works for all".

**Comment by melamit** [comment]
> Choose the correct version and it will work. We don't have a "one file works for all".

do you see 0.4.3 for older versions somewhere?

**Comment by leominerxd** [comment]
strange thing, haven't seen 0.4.3 for other versions, but now i see that versions are strangely listed on the modrinth
