### ISSUE TITLE
Sideways fire is glitchy

### ISSUE THREAD

**Issue by blt-r** [xCollateral/VulkanMod#438]
Minecraft 1.21, vulkanmod 0.4.3, no other mods, nvidia graphics on linux with 550.90.07 driver.

![Screenshot from 2024-06-21 18-48-09](https://github.com/xCollateral/VulkanMod/assets/63462729/0e0f484b-5026-4487-9c7b-7d2be4f35b39)

**Comment by NXTler** [comment]
This is known as axis fighting, most commonly seen as just z fighting. We are aware of this issue, but it's not actively worked on at the moment, as there are bugs/glitches with higher priority.
