### ISSUE TITLE
Incompatible and compatible list of mods

### ISSUE THREAD

**Issue by Zorklis** [xCollateral/VulkanMod#46]
### Testing on VulkanMod 0.4.4 (on 1.21 MC/Fabric.) underway.

Hopefully my testing is useful to someone. Some mods might not function properly but these are the ones that didn't crash on world load. 

### **!!!Comment which mods you tested but are not listed here!!!** 

or not. I'm just a sign.

**Incompatible:**
=========
- autohud-6.6.2+1.20.4-fabric (Doesn't crash in main menu/ Crash during world load)
- astrocraft-1.3.2+1.21
- bedrodium-0.2.3 (requires sodium)
- better-clouds-1.5.7+1.20.4 (crash/ Marked as incompatible.)
- dark-loading-screen-1.6.14 (crashes, also lists other mods as caused by)
- Dashloader
- early-loading-screen-0.5.0
- essential_1-3-1-3_fabric_1-20-4
- exordium-fabric-1.2.1-mc1.20.4 (crash upon world load)
- FastMove-1.20.2-1.0.7 (Uses ukulib: ukulib 1.0.1+1.20.2, which causes crash)
- iris-mc1.20.4-1.6.17 (requires sodium)
- indium-1.0.27+mc1.20.1 (requires sodium)

- ImmediatelyFast-Fabric
- ModernUI-Fabric-1.20.4-3.10.1.5-universal
- Raised
- reeses_sodium_options-1.7.2+mc1.20.4-build.102 (requires sodium)
- particle_core-0.1.2+1.20 (crashes, also lists other mods as caused by)
- PickUpNotifier-v20.4.2-1.20.4-Fabric (Crashes in-game.)
- Ping-fabric-1.21-1.12.0 (Only crashes when used)
- sodium-fabric-mc1.20.2-0.5.3
- sodium-extra-0.5.3+mc1.20.2-build.114  (requires sodium)

- Xaeros_Minimap_24.0.3_Fabric_1.20.4 
- XaerosWorldMap_1.38.1_Fabric_1.20.4
- XaeroPlus-2.6+fabric-1.20.4-WM1.38.1-MM24.0.3

?Tiefix

**Compatible:**
=========
+3dplaceablefoodUPDATE-1.1.8 1.20.4 fabric
+abridged-fabric-1.20.x-1.1.1
+abseil-fabric-0.96.4+1.20.4-1.0.1
+accelerated-decay-fabric-84.0.0
+accurate-block-placement-1.2.1
+adorabuild-structures-2.4.0-fabric-1.20.4
+Adorn-5.3.0+1.20.4-fabric
+advancementinfo-1.20.4-fabric0.91.2-1.4
+animated-doors-1.1 (works, same as normally, not good looking)
+aggroindicator-fabric_1.20.4_1.0.0.0_beta1
+AmbientEnvironment-fabric-1.20.2-12.0.0.2
+Antighost
+anvilrestoration-1.20.4-2.2
+appleskin-fabric-mc1.20.3-2.5.1
+architectury-11.1.17-fabric
+astrocraft-1.1.3+1.20.4
+async-pack-scan-0.2.3
?+audio_engine_tweaks-1.2.5-MC1.20.2 build 1 | Not sure on 1.20.4
+automaticdoors-1.20.4-4.6
+autoswitch-8.0.1
+BadOptimizations-2.1.0
+balm-fabric-1.20.4-9.0.6
+BasicShields-1.4.1-1.20.2
+bedrockify-1.9.1+mc1.20.2
+BetterAdvancements-Fabric-1.20.4-0.4.1.5
+BetterAnimationsCollection-v20.4.0-1.20.4-Fabric
+betterbeds-1.3.0-1.19.3
+BetterF3-9.0.2-Fabric-1.20.4
+betterhandbobbing-1.6.4
+betterladdersmod-1.20.x
+bettertaskbar-fabric-mc1.20.2-1.8.0
+birdsboids-1.1.0
+Boids-1.1.1
+Bookshelf-Fabric-1.20.4-23.0.6
+borderless-mining-1.1.9+1.20.2
+bounced-1.20-4.0.0
+c2me-fabric-mc1.20.4-0.2.0+alpha.11.65
+carryon-fabric-1.20.4-2.1.3.13
+cat_jam-fabric-mc1.20-1.2.1
+cherishedworlds-fabric-8.0.1+1.20.4
+cherry-villages-1.0.5
+clienttweaks-fabric-1.20.4-13.0.2
+cloth-config-13.0.121-fabric
+Clumps-fabric-1.20.4-15.0.0.2
+collective-1.20.4-7.40
+colorfulsubtitles-1.4.0
+comforts-fabric-7.2.2+1.20.4
+constantmusic-fabric-1.0.1
+continuity-3.0.0-beta.4+1.20.2
+cosmetica-1.20.4-1.2.8
+cristellib-1.2.4-fabric
+cullleaves-fabric-3.3.0
+cupboard-fabric-1.20.2-2.0
+dangerclose-merged-1.20.4-3.0.0
+dark-graph-1.1.1
+DarkTitleBar-1.2
+Debugify-1.20.4+1.1
+DetailArmorBar-2.6.3+1.20.4-fabric
+doggo-mod-overhauled-6.3.1
+doorknockmod-1.0
+doubledoors-1.20.4-5.4
+draggable_lists-mc1.20.4-1.0.5-build.30
+duckmod-1.0.1
+dungeons-and-taverns-3.1.1
+durabilityplus_1.20-1.0.3
+dynamiccrosshair-7.7+1.20.4-fabric
+dynamiccrosshair-compat-3.7.2+1.20.2
+earlytobed-1.0.4+mc1.20.4
+easiervillagertrading-1.20.4-fabric0.91.2-1.5.4
+eating-animation-1.20+1.9.61
+edgelesschatscreen-1.1.1-fabric1.20
+emi-1.1.4+1.20.4+fabric
+emotecraft-for-MC1.20.4-2.4.0-a.f140890e-fabric
+entityculling-fabric-1.6.4-mc1.20.4
+entity-view-distance-1.2.0+1.20.4
+exlinefurniture-v2.7.2-fabric-1.20.4
+fabric-api-0.96.11+1.20.4
+fabric-language-kotlin-1.10.19+kotlin.1.9.23
+FabricShieldLib-1.7.2-1.20.4
+fairydots-1.0.0
+fallingleaves-1.15.6+1.20.1
+FallingTree-1.20.4-1.20.4.3
+fast-doll-1.4
+fasterrandom-3.0.3
+fastestportals-1.0.4
+fast-ip-ping-mc1.20.4-fabric-v1.0.1
+fastminecart-1.0.0
+fastpaintings-1.20.4-1.2.9-fabric
+Female-Gender-Mod-fabric-1.20.2-3.1
+ferritecore-6.0.3-fabric
+feytweaks-1.20.4-1.2.8
+firstperson-fabric-2.3.4-mc1.20.4
+flamearrows-1.20.4-11-fabric
+forcecloseloadingscreen-2.2.1
+ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric
+frank-1.0.0+1.20.2
+freecam-fabric-modrinth-1.2.3+1.20.4
+freelook-1.1.5
+FuelInfo-2.0+1.20.4
+gamemenuremovegfarb-fabric-mc1.19.4-2.1.2
+geckolib-fabric-1.20.4-4.4.4
+GlitchCore-fabric-1.20.4-1.0.0.59
+guifollowers-1.20.4-3.5
+handcrafted-fabric-1.20.4-3.2.1
+highlight-fabric-1.20.2-2.2.0
+horsearmorstandmod-1.0.2-1.20-1.20.4
+hyperleash-1.1
+infinitetrading-1.20.4-4.3
+inventory-control-tweaks-1.3.29+MC1.20.2-1.20.4
+inventorymanagement-1.5.0+1.20.3
+InvMove-1.20-0.8.5-Fabric
+ivespoken-1.20-2.0.2
+jamlib-fabric-1.0.8+1.20.4
+Kaffee's_Dual_Ride-mc1.20.4-1.1.0
+keepmysoiltilled-1.20.4-2.2
+Kiwi-1.20.4-fabric-13.5.1
+krypton-0.2.6
+lambdynamiclights-2.3.4+1.20.4
+language-reload-1.5.10+1.20.3
+lanterns-belong-on-walls-1.7.0+1.20.4 (requires Statement)
+lazy-language-loader-0.3.5
+leaky-fabric-1.20.1-1.6
+led-1.8.0
+libjf-3.14.3
+lios_overhauled_villages-1.18.2-1.20.4-v0.0.3
+lithium-fabric-mc1.20.4-0.12.1
+locationcopy-mc1.20.4-1.0.4
+Log-Begone-Fabric-1.20.2-1.0.8
+LunaSlimes-1.7.1
+make_bubbles_pop-0.2.0-fabric-mc1.19.4+
+MaxHealthFix-Fabric-1.20.4-15.0.4
+mcw-bridges-3.0.0-mc1.20.4fabric
+mcw-doors-1.1.0-mc1.20.4fabric
+mcw-fences-1.1.1-mc1.20.4fabric
+mcw-furniture-3.2.2-mc1.20.4fabric
+mcw-roofs-2.3.0-mc1.20.4fabric
+mcw-windows-2.2.1-mc1.20.4fabric
+memoryleakfix-fabric-1.17+-1.1.5
+memoryusagescreen-fabric-mc1.20-1.9.0
+mmcmga-1.20.2-1.0
+mobhealthbar-fabric-1.20.x-2.3.0
+modelfix-1.14-fabric
+modernfix-fabric-5.15.0+mc1.20.4
+modmenu-9.0.0
+monolib-fabric-1.20.4-1.0.1
+moonlight-1.20.4-2.10.3-fabric
+moreculling-1.20.4-0.22.1
+MouseTweaks-fabric-mc1.20-2.26
+mousewheelie-1.13.3+mc1.20.4
+moveboats-1.20.4-3.2
+mru-0.4.0+1.20.4
+musicnotification-1.6.1+1.20.4
+mvs-4.1.1-1.20-fabric
+namepain-1.5.3 fabric-1.20.x
+Nimble-1.20.1-fabric-5.0.1
+nohostilesaroundcampfire-1.20.4-5.9
+noisium-merged-2.0.1+mc1.20.x
+NoRealmsButton-1.0.1-fabric
+no-telemetry-1.8.0
+notenoughanimations-fabric-1.7.1-mc1.20.4
+noxesium-1.2.0
+numeralping-1.2.2
+one-click-crafting-1.7.3
+online-emotes-3.0.0+mc1.20.4-fabric
+packedup-1.0.30c-fabric-mc1.20.4
+particle-rain-2.0.8
+ParticleTweaks-1.1.3-Fabric+1.20.2
+passiveshield-1.20.4-3.4
+PetOwner-1.8.6-1.20.2+
+polydecorations-0.2.2+1.20.4
+polymer-bundled-0.7.7+1.20.4
+powershot-1.4.0-1.20.2-fabric
+puffish_skills-0.11.5-1.20.4-fabric
+PuzzlesLib-v20.4.42-1.20.4-Fabric
+quickbench-4.3.0+mc.1.20.4
+rain-grow-1.2
+real-arrow-tip-0.1.0+mc1.20
+redirector-5.0.0
+refined-advancements-1.0.3d
+reimaginedmenus-2.0.0-1.20.4
+removeblockoutline-1.1.2-1.20.1
+resourcefullib-fabric-1.20.4-2.4.10
+restApi-0.10.1-1.20.4-fabric
+rightclickharvest-fabric-4.1.4+1.20.4
+rsec-1.1-1.20.4-fabric
+sbet-1.1.1
+sciophobia-1.0.1
+screenshot_viewer-1.2.2-fabric-mc1.20.4
+seamless-2.2.2-fabric-1.20.4
+servercore-fabric-1.5.0+1.20.4
+shifty-hotbar-mc1.20-1.1
+show-me-your-skin-1.8.0+1.20.4
+shutter-2.0.4-fabric-1.20.4
+sit!-1.1.4+1.20.2-1.20.4
+skinlayers3d-fabric-1.6.2-mc1.20.4
+skiptransitions-1.3.3+mc1.20
+sleepsooner-1.20.4-4.5
+SmoothCoasters-1.20-v2
+smoothskies-1.1.0
+SnowUnderTrees-2.2.0+1.20.4
+stackrefill-1.20.4-4.2
+starlight-1.1.3+fabric.f5dcd1a
+stepup-1.20.4-fabric0.91.2-1.3
+stitched-snow-1.0.7
+StrongerSnowballs-Fabric-1.20.4-16.0.3
+stutterfix-mc1.20.3-0.2.0
+supermartijn642configlib-1.1.8a-fabric-mc1.20.2
+supermartijn642corelib-1.1.17-fabric-mc1.20.3
+SwordBlockingMechanics-v20.4.1-1.20.4-Fabric
+threadtweak-fabric-1.20.4-0.1.2
+through-the-lilypads-gently--mc1.20--1.1.1
+tia-1.20-1.1-fabric
+Tips-Fabric-1.20.4-15.0.4
+trade-cycling-fabric-1.20.4-1.0.11
+translucent-glass-0.1.2
+vectorientation-1.1-1.20.3
+videotape-1.3.0
+villagernames-1.20.4-7.3
+Villainous Fish AI-fabric-1.20.4-1.1
+visualoverhaul-fabric-5.1.0
+vmp-fabric-mc1.20.4-0.2.0+beta.7.139-all
+VulkanMod_1.20.4-0.4.0
+wakes-0.2.2 (But the Main effect is not present/broken)
+weathersync-0.3.1
+webstreamer-1.5.0
+yet-another-config-lib-fabric-3.3.2+1.20.4
+Zoomify-2.13.2

---

Only tested on 1.20.2:
+BetterThirdPerson-Fabric-1.20-1.9.0
+Betterfpsdist
+Clear Skies
+coffwallclimb-1.0.4
+Connectivity
+Couplings
+CraftPresence
+Crops love rain
+Cull clouds
+Durability Viewer
+elytra_trinket-1.0.4
+Enchanced Blocked Entities
+Fastload
+fast-chest-1.4+1.20
+fastminecart-1.0.0
+harvestwithease-1.20.2-7.0.0.2-fabric
+Health care
+Hotbarcycle
+Just Load
+Lazy DFU
+Leave us in peace
+Let me despawn
+Liberty villagers
+Lunade fastanim
+Midnight Controls+midnightlib
+Ngrok
+pickupnotifications-1.6.0+1.20.2
+realistic-rowing-1.0.0
+Robinhood
+RPG Stats
+Shut Up GL Error-fabric-1.20.1-1.0.0
+snowyleavesplus-mc1.20.2-0.1.8
+steppy-1.20-1.0.1
+styled-chat-2.3.0+1.20.2
+Smooth boot
+Smooth Chunk
+Smooth swapping
+Trajectory+Preview-3.2-1.20.1
+trinkets-3.8.0

---

Previously compatible [on 1.19] (not tested since I don't use these):
?Better Biome Blend
?Cull Less Leaves
?Fabric seasons
?Short grass
?Thorium

**Comment by NaiNonTH** [comment]
This mod seems incompatible with the 'Enhanced Block Entities' mod too. Please add it to the list.

**Comment by bghyt** [comment]
Please add Xaro's map mods to the list as it crashed my game upon start

**Comment by Klatch13** [comment]
Добавьте совместимость с Better FPS Distance, если её нет

**Comment by limolipp** [comment]
Dark loading screen and roughly enough items will crash the game upon start. fastchest works without any issues

**Comment by Laky730** [comment]
Distant Horizons is currently incompatible based on my tests. It probably has to do with the fact that it uses heavy OpenGL.

**Comment by ToxicSilent** [comment]
Since sodium has been added to it, it would be nice to add both optifine and optifabric

**Comment by FeminineFemale** [comment]
The mod called Puzzle from https://www.midnightdust.eu/ its in the Fabulously Optimized modpack crashes your game

**Comment by Supertacoz** [comment]
You can add PlayerEX and RelicEX to compatible.

**Comment by Zorklis** [comment]
Updated list of mods I use, tested on 1.19.2

**Comment by NaiNonTH** [comment]
Please add these mods to **Incompatible**
* Cloth Config (game crashes while opening Mod — that uses cloth config as a configuration menu API — Config menu)
* Better Distance FPS (reported to be incompatible with VulkanMod by MixinConflictHelper mod)
* Satin API (shader related and seems pretty abundant with OpenGL stuff), including other mods that Satin API is their dependencies
     * Effective V1.4 and above
     * Blur
* Illuminations
* Wavey Capes (only incompatible with the 'Smooth' cape-waving style)
* Create (Flywheel renderer incompatibility)
* Exordium (The game still runs fine, but in-game UIs are bunches of mess)
* Fabric Skyboxes
* Accurate Maps

**Comment by I-like-Portal-2** [comment]
Appleskin works for me

**Comment by 0PandaDEV** [comment]
Don't work with feather client

**Comment by seriousfreezing** [comment]
Please add these mods to the Incompatible list:
- EnhancedBlockEntities
- Dashloader
- ServerCore
- Canvas
- Exordium
- ImmediatelyFast

**Comment by Zorklis** [comment]
> * ServerCore

Have you tested this recently on your end?
I just tried servercore-fabric-1.3.8+1.20.2 +fabric api + vulkan. ONLY. and this does not crash, does it crash on a server?

**Comment by Zorklis** [comment]
Updated my mod list up to 1.20.2 that don't crash and can be launched and played, though something textures are weird and launch is inconsistent, need more research into what's causing problems.

**Comment by Zorklis** [comment]
[Vazkii](https://modrinth.com/user/Vazkii)'s [Neat ](https://modrinth.com/mod/neat) mod seems to be [crashing](https://github.com/xCollateral/VulkanMod/issues/318)

**Comment by seriousfreezing** [comment]
Well, I had tested it in version 1.19.2. So, probably +1.19.2 solved this crash or something.

**Comment by kiokori-git** [comment]
how is continuity added as compatible if indium and sodium is incompatible, doesn't continuity needs indium? and indium needs sodium.

**Comment by Felix14-v2** [comment]
> how is continuity added as compatible if indium and sodium is incompatible

Continuity requires Indium only if Sodium installed

**Comment by kiokori-git** [comment]
> > how is continuity added as compatible if indium and sodium is incompatible
> 
> Continuity requires Indium only if Sodium installed

oh.
sorry for being dumb then 😅, thanks for telling.
i might actually just misread the warning

**Comment by JL2210** [comment]
Is cloth-config compatible or incompatible? I see it on both lists.

**Comment by Abadodod** [comment]
Add "fabrishot" mod to the incompatible list. Since the game crashes when it takes a large, high resolution screenshot

**Comment by Nitjsefnie** [comment]
Incompatible:
[Wurst](https://github.com/Wurst-Imperium/Wurst7)
[Immersive Portals](https://github.com/iPortalTeam/ImmersivePortalsMod)

**Comment by Nitjsefnie** [comment]
Incompatible: DimDoors

**Comment by Aether-254** [comment]
Please add Flywheel to Incompatible.

Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.minecraft.class_310.method_37274(class_310.java:2424)
	at net.minecraft.class_310.method_22681(class_310.java:2419)
	at net.minecraft.client.main.Main.main(Main.java:220)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at me.towdium.jecharacters.mixin.MixinTransformerDelegate.transformClassBytes(MixinTransformerHook.java:25)
	at me.towdium.jecharacters.mixin.MixinTransformerHook.transformClassBytes(MixinTransformerHook.java:45)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [flywheel.mixins.json:RenderTexturesMixin from mod flywheel] from phase [DEFAULT] in config [flywheel.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on com/mojang/blaze3d/systems/RenderSystem::storeTextureLoc with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::_setShaderTexture(ILnet/minecraft/class_2960;)V merged by net.vulkanmod.mixin.render.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> flywheel.mixins.json:RenderTexturesMixin from mod flywheel -> Prepare Injections ->  -> handler$bpk000$flywheel$storeTextureLoc(ILnet/minecraft/class_2960;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 15 more

**Comment by Kalluyt** [comment]
> Please add Xaro's map mods to the list as it crashed my game upon start

they can't add this by themself, the xaros map works on openGL that's their problem not vulkans ask the devs of xaros map bro vulkan devs can't do anything about openGL because vulkan mod is made to use vulkan drivers

**Comment by Zorklis** [comment]
Potentially, getting crashes. Gonna investigate these:
BetterAnimationsCollection-v20.4.0-1.20.4-Fabric?
PickUpNotifier-v20.4.2-1.20.4-Fabric
PuzzlesLib-v20.4.42-1.20.4-Fabric
SwordBlockingMechanics-v20.4.0-1.20.4-Fabric (requires puzzlelib)
fallingleaves-1.15.6+1.20.1
particle-rain-2.0.8
wakes-0.2.3
feytweaks-1.20.4-1.2.8    ?????????
Adorn?
early-loading-screen-0.5.0 ????
essential_1-3-1-3_fabric_1-20-4 ???
Cosmetica
weathersync
ModernUI - fabric
animated doors
immediately fast
enhancedblockentities
particlecore

**Comment by Zorklis** [comment]
> Is cloth-config compatible or incompatible? I see it on both lists.

I tested on 1.20.4 right now (cloth-config-13.0.121-fabric) and Cloth Config seems to work just fine. Not sure what it was around that time but marking it compatible.

**Comment by pedrodesu** [comment]
Debugify crashes on 1.21

**Comment by Vxn1ty** [comment]
Add Vivecraft to Incompatible it crashes on load

**Comment by xCollateral** [comment]
This list is probably outdated, please refer to the [Incompatible mods list](https://github.com/xCollateral/VulkanMod/wiki/Incompatible-mods) on the wiki.

**Comment by Zorklis** [comment]
> This list is probably outdated, please refer to the [Incompatible mods list](https://github.com/xCollateral/VulkanMod/wiki/Incompatible-mods) on the wiki.

Who cares, this is more to report incompatible mods

**Comment by ViperX-PVR** [comment]
The continuity mod support with it not required indium but, with the continuity mod there's a texture error the, helmet, arrows and UI for spawn eggs.

**Comment by hoovi1234** [comment]
fear not, for i have found a way to use incompatible mods with vulkanmod

step 1. go here https://github.com/pal1000/mesa-dist-win and download the latest release version (release-mingw)
step 2. make a modpack (or download one using modrinth) using vulkanmod
step 3. go to the java installation it uses
step 4. go to mesa in downloads
step 5. copy all files in the x64 folder into the bin in the java installation
step 6. profit

**Comment by A8Cl233395** [comment]
Incompatible with Litematica.

**Comment by sawyerthemiller** [comment]
Will not work on 1.20.1 with celestial mod so :/

**Comment by Pepeshki** [comment]
add flashback to the list of incompatible mods

**Comment by Marvin732** [comment]
Immersive Portals also is not compatible, game refuses to start

**Comment by HopedCrown** [comment]
### Particle Core works completely fine for me. 
No **crashes**, no **logs** suggesting particle core is creating issues...

**Comment by HopedCrown** [comment]
> Incompatible with Litematica.

Works for me in mc1.21.11 and mc26.1.2

**Comment by jntm0fz** [comment]
在我新下载的1.21.11fabric0.19.3中只有ImmediatelyFast v1.14.3、vulkanmod v0.6.8和fabric api 0.141.6,可以正常游玩Minecraft，所以似乎该把ImmediatelyFast从不兼容列表中删去？
另外，在同一环境（已去除ImmediatelyFast）中，GPUBooster或Reflex AntiLag（及其前置，已确认崩溃与其前置无关）与vulkanmod v0.6.8一起安装会导致游戏启动失败

In my newly downloaded 1.21.11-fabric-0.19.3, with only ImmediatelyFast v1.14.3, vulkanmod v0.6.8, and Fabric API 0.141.6 installed, the game runs normally. So, should ImmediatelyFast be removed from the incompatibility list? Additionally, in the same environment (without ImmediatelyFast), installing GPUBooster or Reflex AntiLag (along with their prerequisites; it has been confirmed that the crash is unrelated to those prerequisites) together with vulkanmod v0.6.8 causes the game to fail to launch.
