### ISSUE TITLE
Text Rendering Issues with Polytone

### ISSUE THREAD

**Issue by notabirb1** [xCollateral/VulkanMod#460]
### Describe the bug

When running [Polytone](https://modrinth.com/mod/polytone) and VulkanMod, text renders as randomly-colored rectangles. This is similar to #199, but occurs without any resource packs enabled.

![image](https://github.com/user-attachments/assets/34ee553e-c873-4b23-8cb5-6bdf8962e708)

**System Info:**
OS: Fedora Linux 40
DE: KDE Plasma 6.1.2 Wayland
GPU: Nvidia GT 1030
Driver Version: `555.58.02`
Launcher: Prism Launcher 8.4 (Flatpak)
Minecraft: 1.21
Fabric Loader: 0.15.11
VulkanMod: 0.4.4 (`VulkanMod_1.21-0.4.4.jar`)
Polytone: 2.1.1 (`polytone-1.21-2.1.1-fabric.jar`)

---
I didn't see anything related to the issue in my log files (ignore the missing library for Minecraft's narrator, I'm running the PrismLauncher flatpak, which doesn't seem to include this library by default.)

### Steps to reproduce

1. Install VulkanMod and Polytone
2. Launch the game.

### Log files

[latest.log](https://github.com/user-attachments/files/16257526/latest.log)

**Comment by enpassantcheckmate** [comment]
Polytone is known to have visual glitches with vulkanmod

**Comment by notabirb1** [comment]
I didn't see anything related to Polytone in the issue list, so I figured it was worth reporting. If this is a well-known issue, it should probably be added to the incompatibility list to avoid confusion.

**Comment by enpassantcheckmate** [comment]
It is on the Discord incompatible list so for some reason it is not on the github one

**Comment by thr3343** [comment]
For some reason the Lightmap (For block light) and Text textures are getting swapped, which causes the lightmap to be used for text glyphs, causing the glitch

Unrelated to this issue, but i did open a PR that unintentionally fixes this Polytone bug: https://github.com/xCollateral/VulkanMod/pull/467 
Though will mention that was by complete accident, and that fixing mods was not my original intention with that PR

**Comment by xCollateral** [comment]
Fixed by 5b26cad7
