### ISSUE TITLE
VulkanMod appears to be incompatible with REI.

### ISSUE THREAD

**Issue by wow13524** [xCollateral/VulkanMod#47]
Starting up Minecraft with VulkanMod and REI is fine, but the game crashes once the inventory is opened.

**Comment by teppyboy** [comment]
gib log

**Comment by lospejos** [comment]
I also tested it.

OS: `Windows 10 , 64 bit Build 17763 (10.0.17763.3232)`
Java: 
`JRE version: OpenJDK Runtime Environment Zulu18.32+11-CA (18.0.2+9) (build 18.0.2+9)`
`Java VM: OpenJDK 64-Bit Server VM Zulu18.32+11-CA (18.0.2+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)`
Launcher: `PolyMC 1.4.1`

Mod loader: `Quilted Fabric (qfapi-4.0.0-beta.1_qsl-3.0.0-beta.2_fapi-0.58.5_mc-1.19.1)`
Minecraft `1.19.1`

Mods installed:
```
architectury-6.0.35-fabric (required by REI)
cloth-config-8.0.75-fabric (required by REI)
modmenu-4.0.5 (to manage mods)
notenoughcrashes-4.1.6+1.19-fabric (to get stack deobfuscated traces)
qfapi-4.0.0-beta.1_qsl-3.0.0-beta.2_fapi-0.58.5_mc-1.19.1 (Mod loader)
RoughlyEnoughItems-9.1.520
VulkanMod_1.19-0.1.6+1
```

LWJGL: `version 3.3.1` (not modified after instance creation, default after installation)

New world created successfully, after clicking `E` (open inventory), crash occur.

Minecraft `latest.log` has no error logs, see: `latest.log`: 
[latest.log](https://github.com/xCollateral/VulkanMod/files/9257951/latest.log)

`crash-reports` directory has no crash dumps.

Java crashed and dumped, see `hs_err_pid15608.log`:
[hs_err_pid15608.log](https://github.com/xCollateral/VulkanMod/files/9257992/hs_err_pid15608.log)

It seems like its not a mod crash rather a JVM crash.

**Comment by RoxyCN** [comment]
REI requires OpenGL 
not supported on Vulkan

**Comment by xCollateral** [comment]
It should be fixed.
