### ISSUE TITLE
The 0.4.5-0.4.0.1 Valkan module has serious rendering errors on certain models

### ISSUE THREAD

**Issue by cleanper** [xCollateral/VulkanMod#476]
### Describe the bug

This bug has a serious rendering error where all blocks have no color. Intel (R) core (TM) i3-10100 CPU @ 3.60GHz This is my CPU, GPU graphics card Intel (R) UHD Graphics 630.

### Steps to reproduce

1. Only add Fabricapi0.100.7 and Valkan mod. 2. Launch the game without modifying any configuration. World creation is also the default configuration. 3. Enter archive. 4. Serious rendering error (block rendering error)
![Uploading 2024-07-28_22.59.30.png…]()
![2024-07-28_22 59 36](https://github.com/user-attachments/assets/ae0f389b-15a1-46a2-b241-1a3ac0092518)

### Log files

[latest.log](https://github.com/user-attachments/files/16404157/latest.log)

**Comment by ShadowMC69** [comment]
Also on my laptop with Intel(R) UHD Graphics gpu, sometimes it renders chunks on wrong position or empty (only occured in 0.4.5-0.4.5.1)
![2024-07-28_07 43 58](https://github.com/user-attachments/assets/c39718f7-f5c0-4564-8261-7d5ecbdccce5)

**Comment by gerarzZz** [comment]
That happens to me too, if I keep walking it doesn't matter, sometimes I just reload the chunks and it fixes itself

**Comment by CoelacanthusHex** [comment]
I meet the same issue on Minecraft 1.20.6 with VulkanMod 0.4.2, the problem seems to have gone after downgrading to 0.4.1

**Comment by Edirimuni-Dison-Randul-Silva** [comment]
> That happens to me too, if I keep walking it doesn't matter, sometimes I just reload the chunks and it fixes itself

the main issue also occurs for me to. but when i reload the chunks this happens

![2024-08-09_14 49 38](https://github.com/user-attachments/assets/a425c343-77e6-45a0-bc99-9b7297693986)


Vulkan Instance Version: 1.2.162

system config:
os: Windows 11 - 23H2
cpu: i3-8130U
igpu: Intel UHD 620 
ram: 12 GB

java version: 21
MC version: 1.21
mod version: 0.4.5.1
FabricAPI version: 0.102.0
Fabric Loader version: 0.16.0 & 0.15.11 ( i tried both )
allocated memory : 400MiB - 6144Mib

heres my log:
[Log-latest-09-08-24.txt](https://github.com/user-attachments/files/16559311/Log-latest-09-08-24.txt)

**Comment by NXTler** [comment]
Does this still happen on the newest VulkanMod version. It should be fixed.

**Comment by Edirimuni-Dison-Randul-Silva** [comment]
Can confirm this issue has been resolved 👍

**Comment by NXTler** [comment]
Great, this can be closed.
