### ISSUE TITLE
requires linux arm support (pojavlauncher)

### ISSUE THREAD

**Issue by Furina-imw** [xCollateral/VulkanMod#479]
### Describe the request

Previously, there were some videos on the Youtube platform sharing the vulkan mod (patched) that ran on linux arm (pojavlauncher) and it run very well on my not very powerful phone. but it only stops at version 1.20.4 and they don't post any more videos:( so before the developer of this mod supports linux arm, does anyone know how to patch it? please guide me :(

**Comment by Inverted-Fin** [comment]
> ### Describe the request
> 
> Previously, there were some videos on the Youtube platform sharing the vulkan mod (patched) that ran on linux arm (pojavlauncher) and it run very well on my not very powerful phone. but it only stops at version 1.20.4 and they don't post any more videos:( so before the developer of this mod supports linux arm, does anyone know how to patch it? please guide me :(

hey,I have a patch of linux arm here,and can you try it?

**Comment by Furina-imw** [comment]
Yes. where can i download it

**Comment by Furina-imw** [comment]
Yes! can you give me the link to download it :D

**Comment by ShadowMC69** [comment]
# POJAV ISN'T SUPPORTED #

Lemme warn you, those builds may contains **MALWARE**

**Comment by ThatMG393** [comment]
Please close this issue as Android support has been discontinued a long time ago.
