### ISSUE TITLE
Toggling Fullscreen can crash the game

### ISSUE THREAD

**Issue by christopher317** [xCollateral/VulkanMod#482]
### Bug description

Toggling Fullscreen often crashes the game.

demonstration video:
[crash.webm](https://github.com/user-attachments/assets/1a259b60-73c2-41c4-9802-875c4247c556)

### Game/System info

system config:
OS: Linux Mint 21.3 ( providing this as this could be a linux exclusive bug )
CPU: i5-9600k ( under-clocked because thermals )
GPU: GTX 1660 Super ( 550 drivers )
RAM: 32GB

minecraft info:
version: 1.21
mod version: 0.4.5.1
FabricAPI version: 0.102.0
Fabric Loader version: 0.16.0
Java version: GraalVM 21.0.3+7.1 ( skip compatibility checks enabled, probably doesn't do anything as 1.21 requires Java 21 )
Java args: -XX:+UseZGC
allocated memory: min-512MiB, max-8192MiB

### Steps to reproduce

1. open Minecraft ( doesn't even need to be in a word )
2. toggle Fullscreen with F11 ( may take a few tries, sometimes its immediate )
3. game crash!

### Log files

[latest.log](https://github.com/user-attachments/files/16555230/latest.log)

**Comment by thr3343** [comment]
This is a known cross-platform driver bug on Nvidia, where resizing the window too quickly crashes the game 
_(I have this problem on my GTX 1080 Ti as well)_

I believe this is an actual driver bug and not a VulkanMod bug, as it effects all VulkanMod versions back to 2022, and didn't happen on older Nvidia drivers

The easiest way to produce it ime is to drag a corner of the window to resize it constantly, which crashes the client instantly on my machine _(Linux)_

**Comment by christopher317** [comment]
I kinda thought it might be a Nvida driver bug, unfortunate.

**Comment by thr3343** [comment]
After thinking about this, decided I will try to get a patch PR open in the next few days or so.
Might have an idea on at least stabilising the driver instability on fullscreen

**Comment by thr3343** [comment]
@christopher317 Has been fixed as of upstream, the Nvidia swapchain crash should be done for good now.
