### ISSUE TITLE
Windowed FullScreen Mode can not with "Windows Hardware-Accelerated GPU Scheduling feature"

### ISSUE THREAD

**Issue by Tentou-Reikie** [xCollateral/VulkanMod#484]
### Describe the bug

![image](https://github.com/user-attachments/assets/ba8bdef6-2fd8-4031-a6dc-690ad10b34aa)

### Steps to reproduce

When "Windows Hardware-Accelerated GPU Scheduling feature" is turned on, "Windowed FullScreen Mode" doesn't work correctly, and actually works like a real full-screen mode.

### Log files

[2024-08-13-1.log](https://github.com/user-attachments/files/16595550/2024-08-13-1.log)

**Comment by NXTler** [comment]
Seems to be more of a windows specific issue.
