### ISSUE TITLE
[Bug]Rendering error with Journeymap.

### ISSUE THREAD

**Issue by Tentou-Reikie** [xCollateral/VulkanMod#488]
### Describe the bug

![image](https://github.com/user-attachments/assets/a2f9f2d0-f344-44e2-ad3c-0d7bf3992868)

### Steps to reproduce

Rendering was fine with VulkanMod_1.21-0.4.5.1.jar.
But after updating from VulkanMod_1.21-0.4.5.1.jar to VulkanMod_1.21-0.4.6.jar, there is a rendering error.

### Log files

[latest.log](https://github.com/user-attachments/files/16636584/latest.log)

**Comment by xCollateral** [comment]
Fixed on latest release.
