### ISSUE TITLE
Error -1

### ISSUE THREAD

**Issue by N1krok** [xCollateral/VulkanMod#489]
### Describe the request

Please help when starting a game with a mod : vulkanmod , my game comes out with error -1.

**Comment by N1krok** [comment]
[crash-2024-08-17_12.52.45-client.txt](https://github.com/user-attachments/files/16644018/crash-2024-08-17_12.52.45-client.txt)

**Comment by looplyx1** [comment]
just remove sodium and sodium extra, if this won't work, also try to remove replaymod

**Comment by N1krok** [comment]
Ok ,but I ran a clean version with only a vulcan and the same error.

**Comment by NXTler** [comment]
Try running just VulkanMod with fabric API, send the log if it fails.

**Comment by xCollateral** [comment]
This is an issue tracker not a support forum.

**Comment by err2ror** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/6946bc0d-42ec-4f4e-b524-924c5ee9d7d7" />
hello i found the problem
