### ISSUE TITLE
VulkanMod crashes with EMF because of an overwrite mixin.

### ISSUE THREAD

**Issue by luka05050** [xCollateral/VulkanMod#497]
### Describe the bug

When opening Minecraft (1.21.1) with VulkanMod (0.4.7) and EMF (2.2) the game will crash with a -1 error code.
The creator of EMF, Traben, said that there is an overwrite mixin in the code of VulkanMod when I submitted an issue on his Discord.

### Steps to reproduce

1. Install EMF (2.2) and VulkanMod (0.4.7) on an instance of Minecraft (1.21.1)
2. Run the game
3. The game will crash with a -1 error code.

### Log files

[crash-2024-08-27_15.59.19-client.txt](https://github.com/user-attachments/files/16768349/crash-2024-08-27_15.59.19-client.txt)

**Comment by wutwu2550** [comment]
The same happened to me too. I hope this gets fixed soon.
