### ISSUE TITLE
MacOS Crash

### ISSUE THREAD

**Issue by ItzYell0w** [xCollateral/VulkanMod#498]
I'm not quite sure what I'm doing wrong. I'm using Modrinth Mod Loader, and its updated to the newest version, and it's the only mod installed, yet it still crashed? How do I fix this?
Describe the bug

When opening Minecraft Modrinth Loader(1.21.1) on MacOS with VulkanMod (0.4.7) the game will crash.

Steps to reproduce

Install VulkanMod (0.4.7) on an instance of Minecraft (1.21.1)
Run the game
The game will crash upon start up.

Log files

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-08-29 21:00:53
Description: Initializing game

java.lang.RuntimeException
	at net.vulkanmod.vulkan.device.DeviceManager.init(DeviceManager.java:55)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:146)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:63)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1020)
	at net.minecraft.class_310.<init>(class_310.java:524)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.vulkanmod.vulkan.device.DeviceManager.init(DeviceManager.java:55)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:146)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:63)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1020)
	at net.minecraft.class_310.<init>(class_310.java:524)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Mac OS X (x86_64) version 12.7.6
	Java Version: 21.0.4, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 251363712 bytes (239 MiB) / 704643072 bytes (672 MiB) up to 13690208256 bytes (13056 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz
	Identifier: Intel64 Family 6 Model 62 Stepping 4
	Microarchitecture: Ivy Bridge (Server)
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD FirePro D700
	Graphics card #0 vendor: AMD (0x1002)
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: 0x6798
	Graphics card #0 versionInfo: Revision ID: 0x0000, ROM Revision: 113-C3861J-687, VBIOS Version: 113-C3861XA-028, EFI Driver Version: 01.0D.687, gMux Version: 4.0.11 [3.2.8]
	Graphics card #1 name: AMD FirePro D700
	Graphics card #1 vendor: AMD (0x1002)
	Graphics card #1 VRAM (MiB): 6144.00
	Graphics card #1 deviceId: 0x6798
	Graphics card #1 versionInfo: Revision ID: 0x0000, ROM Revision: 113-C3861J-687, VBIOS Version: 113-C3861XB-028, EFI Driver Version: 01.0D.687, gMux Version: 4.0.11 [3.2.8]
	Memory slot #0 capacity (MiB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MiB): 16384.00
	Virtual memory used (MiB): 8544.22
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 162692.64, total: 239172.41
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 162692.64, total: 239172.41
	Space in storage for io.netty.native.workdir (MiB): available: 162692.64, total: 239172.41
	Space in storage for java.io.tmpdir (MiB): available: 162692.64, total: 239172.41
	Space in storage for workdir (MiB): available: 162692.64, total: 239172.41
	JVM Flags: 1 total; -Xmx13056M
	Launched Version: 1.21.1
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: cocoa
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz

**Comment by AndreaCicca** [comment]
It's the first time that I see this project, I tried to install the mod on Prism launcher + Fabric and it works.

Maybe this is due to the fact that I have previously installed MoltenVK on my machine (Translation layer from Vulkan to Metal).

When I open Prism's logs I can see that is loading some stuff related to VulkanMod 

>[01:21:34] [Render thread/INFO]: == VulkanMod ==
[01:21:34] [Render thread/INFO]: Selecting Platform: MACOS
[01:21:34] [Render thread/INFO]: GLFW: 3.4.0 Cocoa NSGL Null EGL OSMesa monotonic dynamic
[01:21:34] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[01:21:36] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, fabric-api-base, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-loader-v0, fabricloader, vulkanmod

**Comment by ItzYell0w** [comment]
> It's the first time that I see this project, I tried to install the mod on Prism launcher + Fabric and it works.
> 
> Maybe this is due to the fact that I have previously installed MoltenVK on my machine (Translation layer from Vulkan to Metal).

Pardon, but I didn't know I had to install external hardware for the mod to work. Wouldn't that be useful to know in the installation guide?

**Comment by AndreaCicca** [comment]
I think the project assumes that the user has a working Vulkan driver. On MacOS there is no support out of the box because.
The current requirements are very tiny 

>Requirements: A device (GPU) that supports Vulkan, Fabric loader

If you now how to use a terminal the installation of MultenVK is not very hard (couple of commands)

**Comment by ghost** [comment]
> I think the project assumes that the user has a working Vulkan driver. On MacOS there is no support out of the box because. The current requirements are very tiny
> 
> > Requirements: A device (GPU) that supports Vulkan, Fabric loader
> 
> If you now how to use a terminal the installation of MultenVK is not very hard (couple of commands)

You don't need to install MoltenVK to run VulkanMod on macOS, it's bundled with mod. Don't spread misinformation

**Comment by xCollateral** [comment]
This is a issue tracker, not a place to ask for support. If you need support ask for it on the discord's support channels.
