### ISSUE TITLE
Resizing the window freezes the game

### ISSUE THREAD

**Issue by 19MisterX98** [xCollateral/VulkanMod#5]
Linux/Pop os with nvidia graphics card

This is the complete error:
[12:44:52] [Render thread/ERROR]: ########## GL ERROR ##########
[12:44:52] [Render thread/ERROR]: @ Render
[12:44:52] [Render thread/ERROR]: 65538: Cannot set swap interval without a current OpenGL or OpenGL ES context
[12:44:55] [Render thread/INFO]: Stopping!

**Comment by xCollateral** [comment]
Can you send full stacktrace? I can't do much with this log.

**Comment by 19MisterX98** [comment]
it freezes, there is no stacktrace.
Ill record a quick video

**Comment by 19MisterX98** [comment]
https://youtu.be/mn7pMBx4A48

**Comment by polarbub** [comment]
> it freezes, there is no stacktrace. Ill record a quick video

Can you send the whole log?

**Comment by 19MisterX98** [comment]
you can see the whole log in the video there is nothing interesting

**Comment by SpidFightFR** [comment]
I also have a Nvidia GPU and i'm on Archlinux. resizing the window and putting the game in fullscreen crashes the game.
