### ISSUE TITLE
Has a problem with Fabric Indigo Renderer

### ISSUE THREAD

**Issue by NaiNonTH** [xCollateral/VulkanMod#50]
As the title said, I have no idea which part of the renderer isn't compatible with the VulkanMod.

Here are the crash report and log, just in case if you need them.
[crash-2022-07-02_19.09.47-client.txt](https://github.com/xCollateral/VulkanMod/files/9032999/crash-2022-07-02_19.09.47-client.txt)
[latest.log](https://github.com/xCollateral/VulkanMod/files/9033002/latest.log)

If you know where I have to change the Indigo Renderer setting, please tell me. Thank you.

**Comment by alexpeyton** [comment]
You have to set `always-tesselate-blocks=false` in .minecraft/config/fabric/indigo-renderer.properties

**Comment by NaiNonTH** [comment]
> You have to set `always-tesselate-blocks=false` in `.minecraft/config/fabric/indigo-renderer.properties`

Already did so, but unfortunately, it didn't help.

**Comment by NaiNonTH** [comment]
Ah, I forgot to provide the version and system specification.

Minecraft Version: 1.19
VulkanMod Version: 0.1.5+2
OS: Windows 11 Pro 64-bit
CPU: Intel® Core™ i5-8400
GPU: nVIDIA GeForce GTX 1060 6GB GDDR5
Allocated RAM: Maximum 2GB

**Comment by alexpeyton** [comment]
Say maybe FabricSkyboxes cause the issue? I did check through compatible mods, it does not have FabricSkyboxes in there.

**Comment by xCollateral** [comment]
Seems `shaderreload 1.8` is causing the issue, but there might be other mods that are not compatible.

**Comment by NaiNonTH** [comment]
Tried removing both `FabricSkyboxes` and `Shader Reload` mods, but the game showed me this error.
[hs_err_pid9388.log](https://github.com/xCollateral/VulkanMod/files/9033061/hs_err_pid9388.log)

**Comment by NaiNonTH** [comment]
Additionally, removing only `Shader Reload` mod causes an infinite loading screen, in my case.

**Comment by xCollateral** [comment]
If you are using fabulous graphics disable it. If the crash still occurs you'll have to test mods one by one.

**Comment by NaiNonTH** [comment]
After around 2 hours of trial and error and severe eye bleeding, here's my summary:

- These mods are the causes of the crash—or say, incompatible with VulkanMod: `Shader Reload`, `Blur`, `Illuminations`, `Physics Mod`, and `Wavey Capes` (occurs only with 'Smooth' style)
- `FabricSkyboxes` is compatible with this mod; However, it doesn't show the sky correctly.
- Additionally, opening most mods configure menu, however, crashes the game.
- The VulkanMod itself crashes the game upon entering one of my worlds.

As I tested the mod, it kinda makes the game run pretty smooth—on some occasions, better than Sodium. I really hope this mod will be able to co-operate with Sodium and Iris in the future. :)
