### ISSUE TITLE
Mod compatability 

### ISSUE THREAD

**Issue by Mathew420w0** [xCollateral/VulkanMod#51]
it doesn't work with the Sodium, Indium and Iris mods, which would be especially nice because they're mods I use all the time for performance.

**Comment by SupinePandora43** [comment]
I think it should be possible to implement their optimizations in this mod

**Comment by alexpeyton** [comment]
ABSOLUTELY NO AND NEVER WILL BE.
This mod uses VulkanAPI which is completely different to OpenGL which Sodium is using.

**Comment by Mathew420w0** [comment]
Understood, I don't really need sodium with this mod, but I would really like some shaders, any comments on that?

**Comment by alexpeyton** [comment]
> Understood, I don't really need sodium with this mod, but I would really like some shaders, any comments on that?

Shaders are planned in the future.
