### ISSUE TITLE
[Feature Request] Support for dynamic lighting

### ISSUE THREAD

**Issue by Dann50** [xCollateral/VulkanMod#515]
### Describe the request

It'd be very cool if Vulkan mod natively integrates dynamic handheld lighting, as no such mods are compatible with Vulkan mod atm (lambdynlights or ryoamiclights are incompatible)

**Comment by Felix14-v2** [comment]
These mods may get support after the 0.5.0 release. You can already find the testing build with FRAPI support in VulkanMod Discord.

**Comment by NXTler** [comment]
Dynamic light will probably never be implemented into VulkanMod directly, as it can be easily done externally and would only decrease code readability. Lambdynlights and Ryoamiclights developers need to fix the compatibility issue from their side, as far as I know.

**Comment by NXTler** [comment]
~~This can be closed.~~

**Comment by LambdAurora** [comment]
> Dynamic light will probably never be implemented into VulkanMod directly, as it can be easily done externally and would only decrease code readability. Lambdynlights and Ryoamiclights developers need to fix the compatibility issue from their side, we can't do anything.

LambDynamicLights uses `LevelRender.getLightColor(BlockAndTintGetter, BlockState, BlockPos)` as its injection point, and with several versions of similar rendering mods not requiring specific compatibility code anymore, I personally would rather avoid adding yet more fragile injections in my own mod.

Relevant issue on LambDynamicLights' side: LambdAurora/LambDynamicLights#238.

**Comment by xCollateral** [comment]
Fixed by 349de86
