### ISSUE TITLE
Bobby work aproved!

### ISSUE THREAD

**Issue by Likhach42** [xCollateral/VulkanMod#519]
### Describe the request

Booby full working without issues on Minecraft 1.21.1.
OS: Gentoo Linux 2.15 x86_64
Launcher: Prism Launcher
CPU: Ryzen 5 4650G
GPU: Radeon RX Vega 7
Bobby version: 5.2.4+mc1.21

**Comment by xCollateral** [comment]
This does not seem like an issue.
