### ISSUE TITLE
Backport to older versions

### ISSUE THREAD

**Issue by Mathew420w0** [xCollateral/VulkanMod#52]
not an issue but I would like it if you backported to older versions, mainly 1.12.2. :)

**Comment by teppyboy** [comment]
DIY, if you can't then don't open an issue to ask the developer to do that.

**Comment by Mathew420w0** [comment]
I have no idea how to request features so I did it in the issues tab, also I don't know the code, I'm just a Minecraft player.

**Comment by alexpeyton** [comment]
It's really hard, like hard as hell. Bring it on 1.17 is already a nightmare. Now 1.12 requires a lot of work or even impossible since there's only one man doing this project.
