### ISSUE TITLE
A 0.5.0 build for Java 1.20.4

### ISSUE THREAD

**Issue by JayG120** [xCollateral/VulkanMod#523]
### Describe the request

Hi, will there be an additional 0.5.0 of VulkanMod built specifically for MC 1.20.4? Or only the versions that are in the beta right now (1.21.x/1.20/1.20.1)?
![{B2EC714D-0D59-4DE3-BD6C-BD12B39DE587}](https://github.com/user-attachments/assets/f51715c7-dda0-4f10-b49c-a4097a28fb04)

**Comment by xCollateral** [comment]
Currently these are the only supported versions.
