### ISSUE TITLE
Crash at world login

### ISSUE THREAD

**Issue by alexander4308** [xCollateral/VulkanMod#524]
### Describe the bug

I can't log into world

### Steps to reproduce

1. Install with 1.21.1 with Fabric 0.16.7 on Prism Launcher
2. Try to log into world.
...

### Log files

https://paste.nolog.cz/?a37d92fcaa199fa7#HZ1i1kF7T5TPzkDnBFPFFmdnAo3WPqVmCdwwmZU87eBM

**Comment by leominerxd** [comment]
Did you had FabricAPI installed at that time? Starting with 0.5.0-build.1 VulkanMod doesn't depend on it.

**Comment by alexander4308** [comment]
Hidden dependencies in mod projects are not my problem, it creators problem.

**Comment by xCollateral** [comment]
Fixed by ef9388e
