### ISSUE TITLE
Black Grass Border on certain distance.

### ISSUE THREAD

**Issue by ardissaps** [xCollateral/VulkanMod#53]
![image](https://user-images.githubusercontent.com/82106625/177020534-5af6db44-c94a-4753-9633-ceb6c02c9a4d.png)

**Comment by oknacupZero** [comment]
Black border also noticeable on crops at really close range.

**Comment by Etaash-mathamsetty** [comment]
this has been fixed, but it's not been introduced in a release yet

**Comment by ardissaps** [comment]
> this has been fixed, but it's not been introduced in a release yet

Nice! Can't wait!
