### ISSUE TITLE
Signs, heads and held items are becoming red in dark or partially shadowed places

### ISSUE THREAD

**Issue by BlueGradientHorizon** [xCollateral/VulkanMod#539]
### Describe the bug

As stated in the title.

Commit [48dbc22](https://github.com/xCollateral/VulkanMod/commit/48dbc22b5fbdcedf068f17002d25de0e725aac1a) behaviour:
![2024-11-10_19 02 38](https://github.com/user-attachments/assets/a68c48bf-a409-4477-86dd-1dd6efaad99a)

Commit [b56a22d](https://github.com/xCollateral/VulkanMod/commit/b56a22d86a0b2ebb3441f659472c020da8479ae2) behaviour:
![2024-11-10_19 03 46](https://github.com/user-attachments/assets/34ecb34c-9665-4c15-aea2-55500b0a1d8c)

### Steps to reproduce

Just build a box and inside it try placing blocks mentioned earlier and also look at the hand.

### Log files

Will attach if needed.

**Comment by smiRaphi** [comment]
Any entities are red in dark places, not just signs, heads & held items
![img](https://github.com/user-attachments/assets/dec47cc6-784b-49d4-9d9e-b572352023b2)

**Comment by xCollateral** [comment]
It should be fixed.
