### ISSUE TITLE
Does not seem to work properly on 1.18.2, despite VulkanMod being the only mod in the directory, also tried with fabric api just incase, nothing.

### ISSUE THREAD

**Issue by TheRedXD** [xCollateral/VulkanMod#55]
Hello, I was trying to use this mod on my linux system, and it seems like it did not work. Here is some useful information you might need:
![image](https://user-images.githubusercontent.com/56270596/177036087-3a4ca5f9-bdd3-463b-a708-204e7f645a07.png)
These solutions don't make too much sense and I couldn't figure out how to even apply them, nor do they seem to be relevant:
![image](https://user-images.githubusercontent.com/56270596/177036103-7d39a4c6-43f2-4ebd-9ee0-f8f9606f5de7.png)
Bit more info:
![image](https://user-images.githubusercontent.com/56270596/177036108-741edae9-4860-4ada-9c35-ded7d21e5921.png)

OS: Pop!_OS (Linux)
More info:
![image](https://user-images.githubusercontent.com/56270596/177036051-55b8ee5e-9dd2-4236-987e-0e3745261e6a.png)

I'm using fabric loader 0.14.8, 1.18.2; Mod version 0.1.5+2, 1.18.2
Would be glad to receive a response!

**Comment by alexpeyton** [comment]
Did you try to make your Minecraft instance run via dGPU instead of iGPU? Also please make sure to install Vulkan. Seems like it can't find the suitable device (can't find Vulkan in your system).

**Comment by teppyboy** [comment]
Try using PolyMC, because official launcher isn't good for these purposes. (If it still crashes, in PolyMC instance click Upload logs then give us the log url)

**Comment by teppyboy** [comment]
> Did you try to make your Minecraft instance run via dGPU instead of iGPU? Also please make sure to install Vulkan. Seems like it can't find the suitable device (can't find Vulkan in your system).

@alexpeyton I believe even if it's running in iGPU, Pop!_OS will have already installed necessary Vulkan drivers for the system.

**Comment by 19s-fautley-k** [comment]
if it fullscreens it freeses

**Comment by Zorklis** [comment]
Still happening? Try latest

**Comment by xCollateral** [comment]
I'll close it since linux compatibility is greatly improved, if it persists open a new one.
