### ISSUE TITLE
vulkanmod seems to pick llvmpipe as it's default device and not the gpu (it's pretty smart ngl)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [xCollateral/VulkanMod#56]
it decided to use cpu rendering by default, so is there any way to change the device. (this is a linux issue btw)
![image](https://user-images.githubusercontent.com/45927311/177046983-0e90ae3d-028e-43b5-9d58-c9cd6e3e51ff.png)
it is probably caused by my gpu having only 512 MB of vram, but its an igpu so vram does not matter at all!

**Comment by Etaash-mathamsetty** [comment]
the best solution would be to ignore cpu devices when initializing vulkan

**Comment by polarbub** [comment]
Maybe uninstall llvmpipe? Also what does glxinfo -B say? It'll give info about the default gpu.

**Comment by Etaash-mathamsetty** [comment]
> Maybe uninstall llvmpipe? Also what does glxinfo -B say? It'll give info about the default gpu.

default gpu is my igpu, this project's device picker is setup incorrectly
and I don't think I can uninstall llvmpipe in flatpak

**Comment by teppyboy** [comment]
Something wrong with your system, but I think your PR will fix the problem. And don't say it's "smart" just because some code doesn't function properly lol

**Comment by Etaash-mathamsetty** [comment]
> Something wrong with your system, but I think your PR will fix the problem. And don't say it's "smart" just because some code doesn't function properly lol

nothing is wrong with my system lol, and I called it smart because it's the first time I have ever seen a bug like this

**Comment by rogue-rabbit** [comment]
I'm having this same issue on Linux, and I obviously cant just remove LLVM.

**Comment by Etaash-mathamsetty** [comment]
> I'm having this same issue on Linux, and I obviously cant just remove LLVM.

can you try the linked PR?
