### ISSUE TITLE
weird bug (probably swapchain related)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [xCollateral/VulkanMod#59]
idk how to describe this so here is a video (not an obs bug)
it seems to become a problem at low framerates (by low framerates I mean 60 fps)
https://youtu.be/exi1knKT4Ok
edit: there are also some issues with transparency in the grass (#53)

**Comment by Etaash-mathamsetty** [comment]
using VK_PRESENT_MODE_FIFO_KHR fixes the problem (VK_PRESENT_MODE_FIFO_RELAXED_KHR provides less latency)
but that's basically just enabling vsync
also btw VK_PRESENT_MODE_MAILBOX_KHR, is NOT vsync btw if you were planning on using that for vsync. (VK_PRESENT_MODE_FIFO_KHR is actually vsync)

**Comment by xCollateral** [comment]
Should be solved.
