### ISSUE TITLE
Fence expiration time out on i915

### ISSUE THREAD

**Issue by rhjdvsgsgks** [xCollateral/VulkanMod#63]
pretty lag when using this mod with i915. and lot of
```
Fence expiration time out i915-xx:Render thread[yy]:zz!
```
shown in kernel log. some part of texture may looks wrong (fonts) or missing (part of background img shown as red)
![](https://user-images.githubusercontent.com/26178113/177229330-bb22ceb2-f3a3-4a11-bfc7-2d040e894589.png)
renderdoc showes a performance issue
```
Unmapped memory overlaps tiled-only memory region. Taking slow path to mask tiled memory writes
```
happens between `vkResetFences` and `vkQueueSubmit` call

after switching to lavapipe. frame sequence looks incorrect (frame 1234 become 1324).

linux 5.18.8
mesa 8ab1e9826db5
vulkanmod 149f675

**Comment by Etaash-mathamsetty** [comment]
seems to be related to #59, you can download the source code and run it with VK_PRESENT_MODE_FIFO_KHR, instead of VK_PRESENT_MODE_IMMEDIATE_KHR and see if it helps (it's in Vulkan.java)

**Comment by xCollateral** [comment]
Are you using mesa driver?

**Comment by xCollateral** [comment]
I'll mark this as closed, if you still need help you can ask for support on discord.
