### ISSUE TITLE
Fatal Error On Startup (AMD)

### ISSUE THREAD

**Issue by jaquobia** [xCollateral/VulkanMod#66]
SIGFPE (0x8) at pc=0x00007fa4450dee71, pid=104656, tid=104657
OpenJDK Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)
Problematic frame: C  [libvulkan_radeon.so+0xdee71]
OS: EdeavourOS (Arch)
CPU: AMD Ryzen 9 3900X 12-Core Processor, 24 cores
GPU: AMD Radeon RX 5700 XT
Drivers: Mesa/Vulkan-Radeon
[hs_err_pid104656.log](https://github.com/xCollateral/VulkanMod/files/9050568/hs_err_pid104656.log)

**Comment by alexpeyton** [comment]
This is a known issue on AMD Mesa driver.

**Comment by MAIDAMY** [comment]
I just want to let people know why some people can shoot ghosts normally when they play on the simulator, and some people can't shoot ghosts normally when they play on the simulator. You should have a prompt circle with no blue light. Please pay attention to the camera part.

**Comment by MAIDAMY** [comment]
The version I play is the fatal framework of the Japanese version

**Comment by alexpeyton** [comment]
> I just want to let people know why some people can shoot ghosts normally when they play on the simulator, and some people can't shoot ghosts normally when they play on the simulator. You should have a prompt circle with no blue light. Please pay attention to the camera part.

This is the GitHub repo of VulkanMod,  a fabric mod that rewrites Minecraft OpenGL renderer to use Vulkan API. Not the repo/issue you are looking for.

**Comment by xCollateral** [comment]
Same as #73
