### ISSUE TITLE
Locked to 60fps

### ISSUE THREAD

**Issue by OpenSource03** [xCollateral/VulkanMod#68]
My 1.19 instance with only this mod enabled, VSync turned off and FPS set to unlimited seems to be locked to 60fps, just like if VSync is on.

I'm running it on M1 Max Mac Studio with macOS 13 beta 3. Disabling this mod fixes the issue.

**Comment by andreasdc** [comment]
> My 1.19 instance with only this mod enabled, VSync turned off and FPS set to unlimited seems to be locked to 60fps, just like if VSync is on.
> 
> I'm running it on M1 Max Mac Studio with macOS 13 beta 3. Disabling this mod fixes the issue.

How are you checking that?

**Comment by OpenSource03** [comment]
> > My 1.19 instance with only this mod enabled, VSync turned off and FPS set to unlimited seems to be locked to 60fps, just like if VSync is on.
> 
> > 
> 
> > I'm running it on M1 Max Mac Studio with macOS 13 beta 3. Disabling this mod fixes the issue.
> 
> 
> 
> How are you checking that?

How am I checking that?... In f3 debug menu, of course...

**Comment by TheTeggiy** [comment]
I agree, Locked to 60fps

Tested on Fedora Workstation 36 (Linux) GPU: Nvidia Geforce MX130

**Comment by RoxyCN** [comment]
ME TOO 
I also looked 60fps
tell me how to unlock,please

**Comment by Phoenix-Starlight** [comment]
For Nvidia you need to also configure the GPU itself.

**Comment by xCollateral** [comment]
It shouldn't be related to VulkanMod, if this keeps happening on new versions open a new issue.
