### ISSUE TITLE
Screen tearing

### ISSUE THREAD

**Issue by Supertacoz** [xCollateral/VulkanMod#69]
OS: windows 10
hardware: ryzen 7 3700x, rx 6600, monitor with refresh rate set to 60 hz
minecraft version: 1.19
mods active: Cloth config, fabric api, version 0.1.6 of this mod
issue: as the title says, I experience immense screen tearing with this mod, and this is whether I have vsync on or off, and if I manually set the fps to 60, or if i set it to unlimited, it will always have a lot of screen tearing. 
Note: the game also appears to be locked to a maximum of 60 fps, and will not go beyond that.

**Comment by Supertacoz** [comment]
If you want more info, just let me know.

**Comment by Supertacoz** [comment]
Solution kind of found, for both screen tearing and fps cap. by going into AMD adrenalin software settings, then graphics, then setting "wait for vertical refresh" to "on, unless application specifies" will result in screen tearing no longer being an issue so long as fps is set to "unlimited" in game, in which it is no longer capped at 60 fps. if you manually set it to stay at 60 fps, screen tearing returns. Note that vsync is on in game as well.

**Comment by Etaash-mathamsetty** [comment]
> Keep in mind that in game vsync and fps limiter are not working.

the fps limiter works fine for me

**Comment by xCollateral** [comment]
Vsync is now supported.
