### ISSUE TITLE
Unattended return statement in MemoryTypes?

### ISSUE THREAD

**Issue by spike11302000** [xCollateral/VulkanMod#70]
In MemoryTypes.java line 194 theres a return statement that returns from createMemoryTypes before it can set GPU_MEM which makes GPU_MEM null and cause a crash when starting. the game only crashes on some hardware because without this change it runs fine on my desktop but crashes on my laptop, removing this return statement now allows the game to run on my laptop

**Comment by Etaash-mathamsetty** [comment]
looking at the source code, removing the return statement seems like something that wouldn't break anything, so I think you should make a pr that adds this patch.

**Comment by xCollateral** [comment]
I noticed that, thank you for reporting.
