### ISSUE TITLE
JRE error: EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by OverFloyd** [xCollateral/VulkanMod#72]
Hello, I get this weird crash before the main menu screen loads up on my regular instance, where I play vanilla 1.19 with just Fabric and some optimization mods. In this case I just had the Fabric API and Vulkan itself. The log and the crash report are listed below, don't really know what it could be in my instances that causes it to crash. Environment is in the crash report.

[crash-2022-06-12_17.43.03-client.txt](https://github.com/xCollateral/VulkanMod/files/9123044/crash-2022-06-12_17.43.03-client.txt)
[latest.log](https://github.com/xCollateral/VulkanMod/files/9123046/latest.log)

**Comment by Etaash-mathamsetty** [comment]
I would firstly disable all other graphics related mods, since there is a high chance of incomatibility
secondly,
what gpu are you using?

**Comment by xCollateral** [comment]
This should be fixed in new build.

**Comment by OverFloyd** [comment]
I'm using an AMD integrated graphic card and drivers are latest.
Turns out I had fabulous graphics on, so I guess this is a duplicate. As soon as I edited the options txt and set the setting to 1 everything worked just fine
