### ISSUE TITLE
Version 2 just crashes on linux and version 1 has the gamma all messed up

### ISSUE THREAD

**Issue by presi300** [xCollateral/VulkanMod#73]
GPU: RX6600XT
OS: Arch linux (x86/64)

**Comment by orowith2os** [comment]
Having a similar issue, when using the 1.19 mod. The 1.18.2 version opens into a game just fine, but a bit choppy (the game is reporting 120FPS). The 1.19 mod just crashes, here are the resulting logs for 1.19:
[hs_err_pid310.log](https://github.com/xCollateral/VulkanMod/files/9143342/hs_err_pid310.log)
https://mclo.gs/wiH92Nd

I am using Fedora 36 with a Radeon RX 570, with the open source Mesa RADV drivers.
![image](https://user-images.githubusercontent.com/93224879/179812051-c7a4bd32-1262-4f35-b9f1-778bea560344.png)

**Comment by orowith2os** [comment]
I've ran the 1.18 version with MangoHUD loaded, and it seems to run at a stable framerate, but isn't very smooth.
![image](https://user-images.githubusercontent.com/93224879/179813173-3b1e6a2d-94fc-4e1e-ae99-a3b23743d619.png)
