### ISSUE TITLE
Vulkan loader not found. Video card - geforce g105m 

### ISSUE THREAD

**Issue by OlehLohin** [xCollateral/VulkanMod#75]
GLFW error 65542: Vulkan: Loader not found.
Please make sure you have up-to-date drivers (see
aka.ms/mcdriver for instructions).

**Comment by adamf30** [comment]
This GPU does not support Vulkan. As that is a mobile GPU, upgrades can be really difficult.

**Comment by xCollateral** [comment]
Your gpu/driver does not support Vulkan.
