### ISSUE TITLE
Video Freeze on Resize

### ISSUE THREAD

**Issue by commandblock2** [xCollateral/VulkanMod#77]
Video Freeze on Resize
Game version: 1.18.2
Mods:
Fabric API: 0.58.0+1.18.2
VulkanMod: 0.1.6+1 (Downloaded from git release)
platform: Gentoo, X11, KDE(compositor enabled, does not allow application to block compositing), nvidia proprietary driver 515.57 (Quadro P600). 
vulkaninfo: https://pastebin.com/xXN4JBxp
![image](https://user-images.githubusercontent.com/21105626/180641599-40776a99-6adb-4f32-b80e-cda1ebded8f6.png)

![image](https://user-images.githubusercontent.com/21105626/180641462-5f822446-1a6c-4b09-b858-61d295e6d9a5.png)

**Comment by Carterpersall** [comment]
I get the same issue on PopOS

**Comment by 19s-fautley-k** [comment]
I get the same issue on Ubuntu with Cinnamon (pretty much Mint Cinnamon)

**Comment by xCollateral** [comment]
Should be fixed with latest commit
