### ISSUE TITLE
вылетает 

### ISSUE THREAD

**Issue by fedtv1452** [xCollateral/VulkanMod#82]
вылетает при изменения настроек графики

**Comment by hausemaster3734** [comment]
Please write you issue on English.

**Comment by agogus228** [comment]
кинь крашлог

**Comment by fedtv1452** [comment]
crashes when changing graphics settings

**Comment by Felix14-v2** [comment]
Can you provide a log?
<details>
 <summary>ру</summary>
Можешь загрузить логи/краш-репорт?
</details>

**Comment by fedtv1452** [comment]
[crash-2022-08-03_20.38.43-client.txt](https://github.com/xCollateral/VulkanMod/files/9278746/crash-2022-08-03_20.38.43-client.txt)

**Comment by Felix14-v2** [comment]
> [crash-2022-08-03_20.38.43-client.txt](https://github.com/xCollateral/VulkanMod/files/9278746/crash-2022-08-03_20.38.43-client.txt)

It looks like incompatibility with LambDynamicLights, but I could be wrong.
