### ISSUE TITLE
Incorrect colors on screenshots

### ISSUE THREAD

**Issue by toyotokyo** [xCollateral/VulkanMod#83]
### When I take a screenshot in the game using F2, the colors in the screenshot are inverted.
I don't know why this is happening. If someone has such a problem, tell me how to fix it.

![2022-08-04_19 54 51](https://user-images.githubusercontent.com/110603382/182907439-2c1a2da6-90e6-4ffb-8047-8b38e6bacb70.png)

### Mods:
Game version: 1.19
Fabric 0.56.3+1.19
VulkanMod 0.1.6+1
![image](https://user-images.githubusercontent.com/110603382/182907750-7af43f13-3382-41ea-8691-7c3a43656da8.png)

**Comment by xin6672** [comment]
#81

**Comment by xin6672** [comment]
#81 
![:/](https://s1.328888.xyz/2022/08/05/jqqZF.png)
https://discord.com/channels/963180553547419670/974578257993277440/985635039582756885

**Comment by Danjhop4** [comment]
Looks kinda cool
