### ISSUE TITLE
Vulkan Mod For 1.16??

### ISSUE THREAD

**Issue by BadaboomPlay** [xCollateral/VulkanMod#84]

**Comment by BadaboomPlay** [comment]
**Please Made Vulkan Mod For 1.16**

**Comment by Ra2-IFV** [comment]
+1
Add support plz!

**Comment by Truuum** [comment]
+1

**Comment by Hersty** [comment]
1.16.5 plz

**Comment by DastyXT** [comment]
+++

**Comment by DeastSoulja** [comment]
1.16.5 plz :(

**Comment by Timtaran** [comment]
+

**Comment by TheOnlineHero22** [comment]
1.16.5 is needed pls

**Comment by xCollateral** [comment]
As I said previously porting VulkanMod to pre 1.17 is an hard task, i don't know if it's worth. Right now I've other priorities.

**Comment by Ra2-IFV** [comment]
Completed or discarded?
