### ISSUE TITLE
Litematica crash on world load

### ISSUE THREAD

**Issue by RayJinStudio** [xCollateral/VulkanMod#85]
**After adding the Litematica module, the game crashes after loading the world is complete.**

minecraft: 1.18.2

![image](https://user-images.githubusercontent.com/41432965/184314961-e8edc74f-9279-4910-a019-61cc303ed117.png)

**Comment by RayJinStudio** [comment]
This problem seems to occur when executing shader.bind();
![image](https://user-images.githubusercontent.com/41432965/184318467-f5d091eb-4506-4b26-aa2b-667ce704004e.png)

**Comment by RayJinStudio** [comment]
minecraft: 1.19
VulkanMod: 0.1.7

![image](https://user-images.githubusercontent.com/41432965/184792923-1643d8f4-cc90-4a28-8eb9-f36bc4c23402.png)

**Comment by Phoenix-Starlight** [comment]
Because its trying to use OpenGL, not vulkan.

**Comment by xCollateral** [comment]
It's been fixed.
