### ISSUE TITLE
GLFW error 65542: Vulkan: loader not found 

### ISSUE THREAD

**Issue by Valeron-bit** [xCollateral/VulkanMod#96]
![unknown](https://user-images.githubusercontent.com/70327872/186265889-c005d674-0b90-4bbc-af2a-60aac582a06c.png)
how can this be fixed?

**Comment by xCollateral** [comment]
Your gpu/driver probably doesn't support Vulkan. What gpu are you trying to run the mod with?

**Comment by Valeron-bit** [comment]
> Your gpu/driver probably doesn't support Vulkan. What gpu are you trying to run the mod with?

Intel(R) Pentium(R) CPU 2127U @ 1.90GHz   1.90 GHz

**Comment by xCollateral** [comment]
Then that's the case.

**Comment by ZZZZlink** [comment]
Has the problem been solved? I want to know haw to solve it

**Comment by ZZZZlink** [comment]
> Has the problem been solved? I want to know haw to solve it

my cpu is  Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz   2.40 GHz
