### ISSUE TITLE
Crash when switching between gamemodes

### ISSUE THREAD

**Issue by Hypri** [xCollateral/VulkanMod#97]
Game crashes when switching between gamemodes through /gamemode or F3+F4
[1.txt](https://github.com/xCollateral/VulkanMod/files/9425358/1.txt)

**Comment by xCollateral** [comment]
Thank you for reporting this. Turns out it's not gamemode switch but just the entire chat rendering broken on mod's 1.19.2 version. I'll release a fix later.
